### ISSUE TITLE
Profile and address performance issue in apply_all_projects

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#100]
The [Scenario Building Notebook](https://github.com/wsp-sag/network_wrangler/blob/master/notebook/Scenario%20Building%20Example.ipynb) is taking a while to run.  I suspect it is from pre-requisite sorting, but we should confirm by:

Options for profiling include print statements to a log file with times...or more likely using [Python's build-in profiler](https://docs.python.org/3.7/library/profile.html).

**Comment by kulshresthaa** [comment]
@e-lo Scenario building notebook took only ~45 seconds to run. Not clear on why it is taking a while to run on your end...

**Comment by e-lo** [comment]
That's awesome! I wonder if something was wrong with my cache or what was going on on my end.  I'll close this for now.
