### ISSUE TITLE
Mockup runtime with Batch file with control files and reports written

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#103]
Mockup a (working) version of creating a scenario from a batch file using a control file that is functionally same/similar to [Scenario Building Example](https://github.com/wsp-sag/network_wrangler/blob/master/notebook/Scenario%20Building%20Example.ipynb) notebook. 

The purpose of this mockup is to give MetCouncil some options for what it "looks like" to run wrangler.

**Comment by e-lo** [comment]
@kulshresthaa I re-assigned this task to you as well. It shouldn't be too complicated but please let me know if you have questions.

**Comment by kulshresthaa** [comment]
@e-lo Could you explain a bit more as to what needs to be done? Looking for a batch file to mimic what is done in Scenario Building Example notebook? What will control file specify?

**Comment by e-lo** [comment]
The basic idea is for the batch file to be static from run-to-run (scenario build-to-scenario build) with the control file (or a header at the start of the batch file with environment variables) dictating things like:
- file and folder names for input/output files
- base scenarios
- projects to include via tag, name, folder, etc

**Comment by kulshresthaa** [comment]
got it!

**Comment by kulshresthaa** [comment]
Where (directory) should this mock-up be placed?

**Comment by e-lo** [comment]
I'm open to ideas....

A `/bin` folder or the example directory come to mind
