### ISSUE TITLE
Add GH access token to Travis to allow Travis to deploy to gh_pages branch

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#107]
This needs to be completed by somebody with "ownership" privileges to the repo.

Please follow the [directions on the Travis CI site](https://docs.travis-ci.com/user/deployment/pages/) to get an access token into the Travis CI wrangler repository settings so that the following bit of code that I added will (hopefully) then deploy our compiled documentation to GH Pages (thus rendering our read the docs stuff unnecessary)

https://github.com/wsp-sag/network_wrangler/blob/7d83fd37f3995dbc7eb6c8900f7c294ecae7617f/.travis.yml#L15-L26

**Comment by kulshresthaa** [comment]
@e-lo I've added a access token to Travis CI. Tried to build again and it failed to deploy 

Preparing deploy
dpl.3
Deploying application
cd /tmp/d20191017-5040-hfm4v1/work
Initialized empty Git repository in /tmp/d20191017-5040-hfm4v1/work/.git/
Switched to a new branch 'gh-pages'
cd -
cd /tmp/d20191017-5040-hfm4v1/work
**rsync: change_dir "/home/travis/build/wsp-sag/network_wrangler/docs/_build/html" failed: No such file or directory (2)**
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.1]
Could not copy /home/travis/build/wsp-sag/network_wrangler/docs/_build/html.
failed to deploy

**Comment by e-lo** [comment]
Not sure what part wasn't working, but I played around with how the commands are executed and it seems to run fine now and pushes to the [gh_pages branch](https://github.com/wsp-sag/network_wrangler/tree/gh-pages) correctly...yay!

Q: can you adjust the repo setting to make sure https://github.com/wsp-sag/network_wrangler is pointing to the gh_pages branch rather than to the readme on master?

**Comment by kulshresthaa** [comment]
yay!!!

Done 
![image](https://user-images.githubusercontent.com/13478750/67035264-32ef8d00-f0ce-11e9-8b59-0c4d5c865367.png)

**Comment by e-lo** [comment]
hoorah - thanks!
