### ISSUE TITLE
add `as_model_net` method

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#109]
Travel models require some special treatment of certain links. In particular, managed lanes that may exist in the same facility as general purpose lanes often require separate links in order to assign them separate volume/delay functions.

The wrangler network standard stores managed lanes data alongside general purpose lanes. However, these lanes need to be moved to their own facilities in order to be modeled properly.

The `as_model_net` method for the HighwayNetwork class should do the following:

1. Duplicate and offset (by a few feet) nodes and links that have links with an ML_lanes value >0
  -  nodes should be the same travel_model_id s but add 10,000
2. Replace variables on managed lanes, e.g. lanes = ml_lanes
3. Add connector links

**Comment by JonathanEhrlichMC** [comment]
Is 10000 high enough? Confirm open number space.

**Comment by e-lo** [comment]
Yes - we will check this.

**Comment by kulshresthaa** [comment]
@e-lo How will the `geometry` and `locationReferences` attributes be updated for ML links?

geometry
--
LINESTRING (-93.09035489999999 44.961085,   -93.0889873 44.966861)
LINESTRING (-93.0889873 44.966861,   -93.08844310000001 44.9717832)


locationReferences
--
[{'sequence': 1, 'point': [-93.0903549,   44.961085], 'distanceToNextRef': 654.2165089214, 'bearing': 0,   'intersectionId': '66a881ea213db90291f16b653b4ad3c8'}, {'sequence': 2,   'point': [-93.0889873, 44.966861], 'intersectionId':   '1d3e5e7f4d37089b04a2a7f180889d04'}]
[{'sequence': 1, 'point': [-93.0889873,   44.966861], 'distanceToNextRef': 550.3699052403, 'bearing': 0,   'intersectionId': '1d3e5e7f4d37089b04a2a7f180889d04'}, {'sequence': 2,   'point': [-93.0884431, 44.9717832], 'intersectionId':   '1562e4d7ba9e06b9319561f12af780ea'}]

**Comment by e-lo** [comment]
I think they would be copied with a set offset of a few feet so that they
aren't directly on top

**Comment by kulshresthaa** [comment]
connector (access/egress) links will have the attributes same as GP lanes?

**Comment by kulshresthaa** [comment]
@e-lo please review. The attributes which are being set is somewhat hard-coded, because different attributes gets calculated differently. Could be cleanup later but does the job for now.

**Comment by e-lo** [comment]
It works. Can be streamlined later.
