### ISSUE TITLE
create_managed_lane_network() creating NaN entries in shapes_df 

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#124]
`create_managed_lane_network()` seems to create some shapes entries with NaN for geometry and IDs.

Added a hack fix to lasso to .dropna() but this should be fixed in wrangler.

**Comment by kulshresthaa** [comment]
@e-lo `geometry` attribute for new links (managed lanes, access and egress connectors) wasn't getting calculated and therefore it was missing. IDs are missing for some existing shape data too and the code isn't generating id's for new links. Not sure how the ids are defined for shapes or if the id can be retrieved from some other network data (link/nodes).
