### ISSUE TITLE
Check for uniqueness for unique identifiers

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#125]
In a validation step, check for uniqueness in unique identifiers that are set for both nodes and links.

**Comment by kulshresthaa** [comment]
@e-lo is this not already implemented [here](https://github.com/wsp-sag/network_wrangler/blob/master/network_wrangler/RoadwayNetwork.py#L253)?

**Comment by e-lo** [comment]
yes! sorry.
