### ISSUE TITLE
Validation Check  for Connectivity Method

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#128]
Make sure all the components are connected together for each mode (at the very least for Roadway)
Per https://github.com/wsp-sag/network_wrangler/wiki/Network-Validation-Checks

**Comment by kulshresthaa** [comment]
@e-lo the idea to check for connectivity here means that we find nodes (if any) which aren't connected to any links in the network, right?

**Comment by kulshresthaa** [comment]
any useful functions from networkx for this is NOT implemented for a directed graph. I will have to write own function to check for connectivity, that's why wondering the functionality....

**Comment by e-lo** [comment]
Getting an error when running `fig, ax = net.network_connection_plot()`
![image](https://user-images.githubusercontent.com/794787/72853372-0f585780-3c66-11ea-836e-bed8ea802ef5.png)

**Comment by kulshresthaa** [comment]
huh! I have version '2.3' and had no problem with `strongly_connected_component_subgraphs`

Google search: Seems like it's present up till 2.3, and removed in 2.4. :(

**Comment by e-lo** [comment]
Let's see if I can downgrade without wreaking havoc on other things. I'll keep you posted.

**Comment by kulshresthaa** [comment]
dont downgrade, fixed the error. Hope this one works. 

https://networkx.github.io/documentation/networkx-2.3/reference/algorithms/component.html

https://networkx.github.io/documentation/stable/reference/algorithms/generated/networkx.algorithms.components.strongly_connected_components_recursive.html#networkx.algorithms.components.strongly_connected_components_recursive

**Comment by kulshresthaa** [comment]
Done!

**Comment by e-lo** [comment]
Overall this seems to work really well, although I have two requests:

1. There doesn't seem to a way to return the actual nodes that are disconnected so that if I wanted to look in the raw network files I could look at where the connection fails.

2. Could you elaborate on what exactly `ignore_end_nodes` means? In particular, this map seems to show that a zillion roadway nodes would be disconnected end-nodes...which aren't on the edge of the network so I'm wondering if something odd is going on?

![image](https://user-images.githubusercontent.com/794787/73124232-cc400200-3f4d-11ea-8019-9f80ad51b39d.png)

**Comment by e-lo** [comment]
One more question: do the colors on the map mean anything?

**Comment by kulshresthaa** [comment]
> One more question: do the colors on the map mean anything?

Colors does not mean anything.. just random colors to show different disconnected sub-graphs!

**Comment by kulshresthaa** [comment]
> 1. There doesn't seem to a way to return the actual nodes that are disconnected so that if I wanted to look in the raw network files I could look at where the connection fails.

Done. method returning both plot and list of nodes now.

**Comment by kulshresthaa** [comment]
> 2\. Could you elaborate on what exactly `ignore_end_nodes` means? In particular, this map seems to show that a zillion roadway nodes would be disconnected end-nodes...which aren't on the edge of the network so I'm wondering if something odd is going on?

We are identifying the strongly connected components in the graph, A graph is strongly connected if each vertex is reachable from every other vertex. If the graph is strongly connected, `strongly_connected_components` returns one big graph, otherwise it returns a list of subset nodes/graphs which are "strongly connected". 

It returns single nodes too (if any) and I thought those single nodes are the end nodes of one-way links or something like that, as those nodes are not "connected" to other nodes. That's where the flag `ignore_end_nodes` is used to drop those single nodes from the list of sub-graph. For our connectivity purpose we don't necessarily want to highlight those one-way link end nodes and I am therefore highlighting two or more nodes sub-graph (by default `ignore_end_nodes` True)

`net.network_connection_plot(mode = "drive", ignore_end_nodes = False)` looks odd and will need to investigate what is going on with those end nodes for "drive" network. If they all are those one-way end nodes or something else!

**Comment by kulshresthaa** [comment]
done in 40c5aaac5c55ceaf0c15fd190e8509d2e5d94a58 and 05fc61876ca13a544b6e06a5b35a29bbbd289809.

found the issue! when mode was specified, I was only filtering out the links and NOT filtering out the nodes. Now, this looks OK, with all of highlighted nodes being the end nodes. 

![image](https://user-images.githubusercontent.com/13478750/73226282-5641c380-4124-11ea-82ff-8440b5409515.png)

**Comment by e-lo** [comment]
> Colors does not mean anything.. just random colors to show different disconnected sub-graphs!

--> meaning that colors near each other that are the same color are likely part of the same subgraph?

**Comment by e-lo** [comment]
> Now, this looks OK, with all of highlighted nodes being the end nodes.

--> much better, yay!

**Comment by e-lo** [comment]
> Done. method returning both plot and list of nodes now.

Awesome, thanks! I might do some slight reworking of the API because:
A) we should be able to get the list of nodes from the og method rather than plot(), and 

B) I'm getting some errors when I run *sometimes* (always the worst)

standby.

**Comment by kulshresthaa** [comment]
> > Colors does not mean anything.. just random colors to show different disconnected sub-graphs!
> 
> --> meaning that colors near each other that are the same color are likely part of the same subgraph?

CORRECTION: Nodes of same "disconnected" sub-graph are same color.

**Comment by e-lo** [comment]
All done!
