### ISSUE TITLE
Scenario creation report

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#129]
Per: https://github.com/wsp-sag/network_wrangler/wiki/Network-Validation-Checks

**Comment by kulshresthaa** [comment]
@e-lo Can you help me with setting up a separate logger in the code which is only used to log the scenario creation report?

**Comment by kulshresthaa** [comment]
@e-lo Help needed to setup a new logger just for scenario log summary [here](https://github.com/wsp-sag/network_wrangler/blob/sprint8_ak/network_wrangler/Scenario.py#L560). :)

**Comment by e-lo** [comment]
Howdy! I'm not sure of how to set up another logger necessarily (although google might?), but you could just write it to a txt file...

**Comment by kulshresthaa** [comment]
done! writing to a text file.
