### ISSUE TITLE
Visual Validation Report

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#132]
To show how projects that have been implemented:

Per https://github.com/wsp-sag/network_wrangler/wiki/Network-Validation-Checks

**Comment by e-lo** [comment]
Overall this is really great.

Could you please make sure you can see all the relevant info though?  I think this is just a settings issue . but it cuts off:

![image](https://user-images.githubusercontent.com/794787/73116628-548eba80-3eee-11ea-970f-fd613165cf33.png)

**Comment by kulshresthaa** [comment]
done!
`pd.set_option('display.max_colwidth', 1000)`
