### ISSUE TITLE
Trim transit to St Paul area

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#138]
+ add a light rail segment

**Comment by i-am-sijia** [comment]
Are you using the network from [develop branch](https://github.com/wsp-sag/network_wrangler/tree/develop/examples/stpaul)?

**Comment by e-lo** [comment]
I see that you clipped some, but there are still stops that are outside of St Paul, i.e.

`50212,,Lake St W & Girard Ave S,Far side E,44.948311,-93.296729,`

https://raw.githubusercontent.com/wsp-sag/network_wrangler/develop/examples/stpaul/stops.txt
