### ISSUE TITLE
shshReferenceId not ShStReferenceId

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#139]
I think?  
If so, lets make sure that change proliferates throughout the networks.

**Comment by i-am-sijia** [comment]
Are you using the network from [develop branch](https://github.com/wsp-sag/network_wrangler/tree/develop/examples/stpaul)?

**Comment by e-lo** [comment]
I'm on sprint8_ak

**Comment by i-am-sijia** [comment]
![image](https://user-images.githubusercontent.com/28812722/72930113-3cba0980-3d29-11ea-8d1c-1c4fadabe7c0.png)

sprint8_ak has `shstReferenceId`

**Comment by i-am-sijia** [comment]
Actually, are you referring to the `node.geojson`?  It has a key `ShStReferenceId`.   Wiki has it:

![image](https://user-images.githubusercontent.com/28812722/72932656-2e222100-3d2e-11ea-9cd5-160cb7632832.png)

**Comment by e-lo** [comment]
I must have meant node :-/ sorry! 

Well we should be consistent with what shared streets uses and across links and nodes. Which is it?

**Comment by i-am-sijia** [comment]
just `id`

https://github.com/sharedstreets/sharedstreets-ref-system/blob/00e8a872ef9cd62d974552a43bab32502eea181f/proto/sharedstreets.proto#L107

**Comment by e-lo** [comment]
I think it is `shstReferenceID` per [this post](https://medium.com/sharedstreets/getting-started-with-the-sharedstreets-referencing-system-matching-a-citys-gis-data-2ee2577604e3)

**Comment by e-lo** [comment]
I will change in wiki and elsewhere as I find...

**Comment by i-am-sijia** [comment]
I'm looking at their [referencing system doc](https://github.com/sharedstreets/sharedstreets-ref-system).  That post talks about the return of shst match, which I found somehow does not use the same names as in their ref system.

IF to be consistent with ref system, we still need to change:

node.geojson:
- `id` not `ShStReferenceId`
- `outboundReferenceIds `not `outboundReferenceId`
- `inboundReferenceIds` not `inboundReferenceId`

link.json:
- `geometryId` not `shstGeometryId`

shape.geojson:
- `fromIntersectionId` not `shstFromIntersectionId`
- `toIntersectionId` not `shstToIntersectionId`

**Comment by i-am-sijia** [comment]
`shstReferenceId` in that post is referring to links I think?

**Comment by e-lo** [comment]
So would you propose that we make all the changes in your reply above?

**Comment by i-am-sijia** [comment]
with two exception, I like:

node.geojson:
- `shstReferenceId`

link.json:
- `shstGeometryId`

but that means we will not be consistent with their doc...

**Comment by e-lo** [comment]
I'm fine with that.
