### ISSUE TITLE
Apply simple roadway feature change

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#14]
Change the network object according to the [`1_simple_roadway_attribute_change`](https://github.com/wsp-sag/network_wrangler/blob/master/example/stpaul/project_cards/1_simple_roadway_attribute_change.yml) project card.

Should be able to be tested with something like: `roadway_network_object.apply_simple_network_change(file='1_simple_roadway_attribute_change')`

**Comment by chryssac** [comment]
@e-lo is this project card decreasing the lanes from 3 to 2?

**Comment by e-lo** [comment]
yup

**Comment by chryssac** [comment]
okay st paul link.json it has 2 lanes for that link... do we want to update the card or the json?

**Comment by chryssac** [comment]
@e-lo are we passing a project card or a string to a project card file to the method?

**Comment by e-lo** [comment]
egads! it doesn't have 2 in real life...but for now please update the card.

**Comment by JonathanEhrlichMC** [comment]
I'm interested to know what happens (or should happen) when an assumption of the project card is not true
