### ISSUE TITLE
Missing AB Nodes in StPaul network

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#140]
Got:
```python
ValueError: IDs in network not unique
```

Reason seems to be: 
![image](https://user-images.githubusercontent.com/794787/72926739-c6f27580-3d09-11ea-87b3-35738b0e84b4.png)

**Comment by i-am-sijia** [comment]
I don't see those links in the St Paul network, are you using the latest network from [develop branch](https://github.com/wsp-sag/network_wrangler/tree/develop/examples/stpaul)?

**Comment by e-lo** [comment]
sprint8_ak branch

I wonder if these were created somehow?

**Comment by e-lo** [comment]
@i-am-sijia - i think these were actually created network links, so let's add in @kulshresthaa and remove you from being responsible :-)

**Comment by kulshresthaa** [comment]
@e-lo which project cards you applied to create the my_scenario from base network?

**Comment by e-lo** [comment]
13_simple_roadway_delete_change.yml
9_simple_transit_attribute_change.yml
1_simple_roadway_attribute_change.yml
10_simple_roadway_add_change.yml
8_simple_transit_attribute_change.yml
4_simple_managed_lane.yml
7_simple_transit_attribute_change.yml

**Comment by kulshresthaa** [comment]
it is coming from applying the project card `10_simple_roadway_add_change.yml`, which is adding those two links with `model_link_id` 404982 and 407042.

The issue is that project card does NOT define the A and B attributes for those new links. 

Can A and B be computed or they have to be defined for new roadways? I forgot, what are A and B?

**Comment by e-lo** [comment]
A and B are the model node ids.
We need to create stable ones. I had forgotten about: https://github.com/wsp-sag/network_wrangler/issues/93

I think we decided that for now it seems like we should require them in the project card file so that we aren't rolling the dice each time.  

For the particular example it looks like u and v should actually be A and B.  @i-am-sijia  can you confirm?

**Comment by e-lo** [comment]
Changed UV to AB.

**Comment by i-am-sijia** [comment]
Yes, Lasso writes out A, B in project cards.
