### ISSUE TITLE
Duplicated apply method in TransitNetwork

### ISSUE THREAD

**Issue by kulshresthaa** [wsp-sag/network_wrangler#141]
`apply` is duplicated in TransitNetwork - [1](https://github.com/wsp-sag/network_wrangler/blob/master/network_wrangler/TransitNetwork.py#L224) and [2](https://github.com/wsp-sag/network_wrangler/blob/master/network_wrangler/TransitNetwork.py#L169)

Based on the comments and code, 2 appear older when managed lane was not implement in transit

**Comment by kulshresthaa** [comment]
removed duplicated code.

**Comment by e-lo** [comment]
Great sleuthing!
