### ISSUE TITLE
Check for same AB combo when adding links

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#142]
When applying a road addition project, fail when AB is same as AB already in network.

**Comment by kulshresthaa** [comment]
if multiple links are being added in the project card and only one link has same AB as AB already in the network. Does the check fails applying the entire project card or add all the valid links and logs error for that one link?

**Comment by e-lo** [comment]
I'm not sure it matters since it will be a fatal error? That said we will
want the duplicate ABs to be printed in the error code.

**Comment by kulshresthaa** [comment]
done!

**Comment by e-lo** [comment]
Awesome! I just checked it out and seems to work great. Thanks for adding a test. I just added a [@py.mark.xfail](http://doc.pytest.org/en/latest/skipping.html) marker to it so that we can run it in travis and expect it to fail.
