### ISSUE TITLE
walk links that connect to nodes that are not walk nodes

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#145]
The network connectivity tools that @kulshresthaa put together have been helpful in finding a few things with the network (thanks!).

This issue notes that there are nodes (rail nodes, mainly) which have walk access links to them...but are not marked as a walk_node in the network.  Thus, when filtering nodes by mode, they are filtered out.

![image](https://user-images.githubusercontent.com/794787/73315335-a97b4b00-41e4-11ea-8cbe-e429a5916d25.png)

![image](https://user-images.githubusercontent.com/794787/73315371-bf890b80-41e4-11ea-80f9-e470dc34e476.png)

There are two options here (that I can think of):

1. mark all these nodes as also being `walk_nodes` (although technically this is a simplification)

2. when filtering networks by mode, keep all the nodes and don't filter by mode.

I will implement #2 (easy fix) right now but I'm wondering if we should consider this a network error and address #1...or not.  Thoughts?

**Comment by i-am-sijia** [comment]
I missed flagging transit nodes to be walk accessible after adding the walk access links.  I will fix this.  Thanks!
