### ISSUE TITLE
Add new stop if required for routing change.

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#147]
Right now we get a value error if something isn't already listed as a stop and we try and make it one. 

Desired behavior would be to create a new stop.

```python
# If node IDs in properties["set_stops"] are not already
            # in stops.txt, create a new stop_id for them in stops
            if any(
                x not in stops[TransitNetwork.STOPS_FOREIGN_KEY].tolist()
                for x in properties["set_stops"]
            ):
                # FIXME
                WranglerLogger.error(
                    "Node ID is used that does not have an existing stop."
                )
                raise ValueError
```

**Comment by josiekre** [comment]
What ID system do I assume for creating a new Node ID? I assume a UUID would break Cube.

**Comment by e-lo** [comment]
Hah, yes...no UUIDs here. The stop node ID should be the same as the node ID in the network.

**Comment by josiekre** [comment]
Fast reply-- I answered my own question by realizing the model node ID will already be provided. I need to make up the GTFS stop_id and get a lat/lon. So I'm getting an example scenario loaded up now to refresh my mind on where all that is stored. 

Looks like my conda env needs updating to add a new `folium` dependency.

**Comment by josiekre** [comment]
Anyway, getting up to speed... I'll let you know if I get stuck.

**Comment by josiekre** [comment]
Do you have a test already built for this (hence why the issue needed to be fixed), or should I create new tests?

**Comment by josiekre** [comment]
Test on `147 Add new stop if req for routing change` branch.

**Comment by josiekre** [comment]
Test on `147_add_new_stop_if_req_for_routing_change` branch.
