### ISSUE TITLE
Update tests in `test_transit_with_roadway.py`

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#148]
With the network update, most of the tests in `test_transit_with_roadway.py` don't work anymore.

When fixed, please remove `pytest.mark.skip()` function decorator.

**Comment by e-lo** [comment]
@i-am-sijia I believe this is still outstanding? Not super high priority but something we need to 'tick off'

**Comment by i-am-sijia** [comment]
@e-lo 

It passed all tests with updated network and examples, with one exception:

I think there's still an issue with network wrangler, as I saw this in the comment:

> A new node ID (not in stops.txt) should fail right now

sounds like the functionality of adding a stop is not supported right now.

**Comment by e-lo** [comment]
Should work now in v1
