### ISSUE TITLE
Problem with fiona

### ISSUE THREAD

**Issue by jhelsel11** [wsp-sag/network_wrangler#152]
I'm trying to install network wrangler using the instructions in the readme. I'm getting hung up trying to install fiona. It appears that this can be solved using a local wheel file (https://stackoverflow.com/questions/54759284/provide-a-path-to-gdal-config-using-a-gdal-config-environment-variable-error-whi). 

Have either of you run into this issue before? Is there a reason not to use the 1.8.4 64 bit whl file? I haven't worked with this library before so I don't know what dependencies it might disrupt in network-wrangler or why you might prefer the 32 bit version..

![image](https://user-images.githubusercontent.com/29383881/73982166-f354e700-48f0-11ea-8f74-5a42958fb0fc.png)

**Comment by e-lo** [comment]
Howdy! PIP doesn't do a good job of this, but conda does a better job. I believe all the instructions say to use conda but LMK if I forgot a place?

You should be able to run:
```bash
conda install rtree 
pip install network_wrangler
```

**Comment by jhelsel11** [comment]
I'm not sure exactly how but I was able to install Fiona by itself (it failed once and the wheel file didn't work but conda install Fiona worked the 3rd? time I tried) and that seems to have done the trick.

**Comment by e-lo** [comment]
The part of fiona that was having trouble was GDAL, which conda should install correctly but pip wont on windows. I'll update the readme to recommend using conda for fiona,  geopandas, and shapely (the troublesome trio) 

See this for similar issue:
https://stackoverflow.com/questions/54734667/error-installing-geopandas-a-gdal-api-version-must-be-specified-in-anaconda/54734864#54734864

**Comment by jhelsel11** [comment]
@e-lo, can we change the readme instructions to only ask for rtree and geopandas? conda install geopandas installs fiona and shapely.
