### ISSUE TITLE
Would like to add attributes to managed lane only

### ISSUE THREAD

**Issue by jhelsel11** [wsp-sag/network_wrangler#159]
We would like to add an attribute to the managed lane only (e.g. HOV for met council).

**Comment by e-lo** [comment]
Just confirmed that this functionality actually already exists in [`create_managed_lanes_network`](https://github.com/wsp-sag/network_wrangler/blob/master/network_wrangler/RoadwayNetwork.py#L1656)

https://github.com/wsp-sag/network_wrangler/blob/4fae96b0ee9785639587ceae2fe196c727097e3d/network_wrangler/RoadwayNetwork.py#L1678
