### ISSUE TITLE
Check for pre-, co-requisites, and conflicts

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#16]
Within the scenario object, check for pre-requisites, co-requisites, and conflicts.

Expected behavior:
- should fail after all are examined if there are any pre-requisites or co-requisites missing
- should fail after all are examined if there are any conflicting projects
- allow an override flag to turn the fail --> warning
- should order the list of project cards such that they are in order based on:
   - year
   - pre-requisites (warn in log any years that are out-of-order)

**Comment by kulshresthaa** [comment]
@e-lo Could you tell me bit more about the issue, so that I can get started on this one?

**Comment by e-lo** [comment]
The basic idea is that you can control how projects interact with each other by specifying one or more of the following:
- Prerequisites: if project B requires project A as a prerequisite
  - make sure that project A is specified in the scenario (warn or fail if not)
  - make sure project A is applied before project B (log this as an info item)
- Corequisites:  if project B requires project A as a corequisite
  - make sure that project A is specified in the scenario (warn or fail if not)
- Conflicts: if project B specifies that project A is a conflict
 - make sure that project A is not included in the scenario ( fail if not)

**Comment by kulshresthaa** [comment]
How do we know what is included in the "scenario". where will it be specified?

**Comment by e-lo** [comment]
It should be held in the [Scenario object](https://github.com/wsp-sag/network_wrangler/blob/786d617d75ae5f4d4d30e3b2044033feab380655/network_wrangler/Scenario.py#L10), which doesn't exist in full form yet.
For now, lets assume that:
 - `self.project_cards` is an ordered list of projects in the order in which they would be applied
 - The prerequisites, co-requisites and conflicts are held in some sort of dict structure which is appended when a project card is added.

https://github.com/wsp-sag/network_wrangler/blob/786d617d75ae5f4d4d30e3b2044033feab380655/network_wrangler/Scenario.py#L27-L30

These might not be ideal assumptions so I encourage you to find improvements so long as they don't diminish usability.

**Comment by kulshresthaa** [comment]
last question for now :-)
what is a base scenario in the [scenario object](https://github.com/wsp-sag/network_wrangler/blob/786d617d75ae5f4d4d30e3b2044033feab380655/network_wrangler/Scenario.py#L10). What is stored in `base_scenario` as a dict?

**Comment by e-lo** [comment]
What, this helpful documentation wasn't enough? :-)
https://github.com/wsp-sag/network_wrangler/blob/786d617d75ae5f4d4d30e3b2044033feab380655/network_wrangler/Scenario.py#L38

The base scenario is a dictionary capable of describing a scenario from which you are tiering. At a minimum, it lists a highway and transit network. Additionally, it could contain information about the projects that have already been implemented.  

An example API would be:
```python
base_scenario = {'highway_network'=base_hwy . ,# HwyObject?
   'transit_network'= base_transit, #Transit network object or files??
   'project_list'= [`atlantis_transit_signal_priority`]} . # list of projects already applied?  could be structured in other ways
card_directory = 'path\to\project\cards'
build_scenario = create_scenario(base_scenario, card_directory, project_card_list = ['atlantis_brt_project`])
```
I meant to work on the Scenario object so that more of this was functioning/obvious but haven't gotten around to it yet. Sorry!

**Comment by e-lo** [comment]
This is working within the PR and passes all current tests locally. PR:  https://github.com/wsp-sag/network_wrangler/pull/47
