### ISSUE TITLE
Transit shape check validation is checking nodes, not links or shapes

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#168]
Right now, the method to check the transit shapes is just looking to see if all the node ids exist in the network, but that is insufficient to examine if:

1. all the links are there
2. all the links in a shape are connected
3. all of the above takes place where the mode=transit

Since node comparison is a nice quick check, let's do that first and if it passes then move on to links and if that passes move on to shapes.

**Comment by kulshresthaa** [comment]
@e-lo Can you tell me if my understanding for checking if all the links in transit shapes are there in the network is correct?

Shapes dataframe:
![image](https://user-images.githubusercontent.com/13478750/77946791-c4ffe200-7277-11ea-9f28-0d1c833d7fca.png)

For each shape_id, do I need to look at the `shape_pt_sequence` and then form a link (b/w `shape_model_node_id`) and see if that links exist in the roadway networks links_df?

E.g., point sequence 55 - 56 -> link from node 152495 to node 151635 and then check links_df for a link with A as 152495 and B as 151635...
![image](https://user-images.githubusercontent.com/13478750/77947227-769f1300-7278-11ea-94f5-4da1d0e0d81f.png)

**Comment by kulshresthaa** [comment]
@e-lo Also, how to tell (from the shapes dataframe) if the all the links in the shape are connected?

**Comment by e-lo** [comment]
> For each shape_id, do I need to look at the shape_pt_sequence and then form a link (b/w shape_model_node_id) and see if that links exist in the roadway networks links_df?
> 
> E.g., point sequence 55 - 56 -> link from node 152495 to node 151635 and then check links_df for a link with A as 152495 and B as 151635...

That's right. You should be able to do it fairly efficiently by sorting the shapes_ids, then doing an merge and offset on the `model_node_id` and then merging the links_df.

**Comment by e-lo** [comment]
> Also, how to tell (from the shapes dataframe) if the all the links in the shape are connected?

Now that I am thinking about this, if the shape lists nodes A, B, C and link A-B exists and so does B-C, then by definition A-B-C are connected...so this is redundant to the step discussed above.

**Comment by kulshresthaa** [comment]
> 3\. all of the above takes place where the mode=transit

What about this one?

**Comment by e-lo** [comment]
Yes. That should still be a requirement

**Comment by kulshresthaa** [comment]
sorry, I meant what should be checked for this?

**Comment by e-lo** [comment]
In the links_df you should make sure that transit is allowed

**Comment by kulshresthaa** [comment]
Done. Please review [here](https://github.com/wsp-sag/network_wrangler/blob/develop/network_wrangler/transitnetwork.py#L257). 

Looks like the `transit_access` flag is not coded correctly as most of the shape links does not allow transit (`transit_access` = 0)?

**Comment by e-lo** [comment]
> Looks like the transit_access flag is not coded correctly as most of the shape links does not allow transit (transit_access = 0)? 

I'll create a new issue for this. cc: @i-am-sijia

**Comment by e-lo** [comment]
Just reviewed your commits and have a few comments. One for style/speed and another is a bug that must be fixed in order to run.

**Comment by e-lo** [comment]
Per our stand-up discussion, network will be revised to have flags:
`bus_only` and `rail_only`

Transit network should be filtered to have either:
`drive_access`, `bus_only`, or `rail_only`

**Comment by kulshresthaa** [comment]
to confirm, one of these fields should be equal to 1 in roadway network for the transit shapes?

**Comment by e-lo** [comment]
right

**Comment by e-lo** [comment]
LGTM
