### ISSUE TITLE
Include managed lane flag for the managed lane created out of a project card

### ISSUE THREAD

**Issue by jhelsel11** [wsp-sag/network_wrangler#171]
Split of lasso issue [#67](https://github.com/wsp-sag/Lasso/issues/67).

Main issue: once managed lanes are created via a project card, the manged lane needs a flag to distinguish it from the general purpose lane. (Right now, both appear to have the same values except for number of lanes and the link ids are separated by a scalar.)

**Comment by kulshresthaa** [comment]
@e-lo I have made the code changes to keep managed lane flag. Just need to know the name of the variable for the flag.

**Comment by e-lo** [comment]
Per Dave's suggestion, variable will be `managed`

**Comment by e-lo** [comment]
I think this can be closed?

**Comment by jhelsel11** [comment]
I agree.
