### ISSUE TITLE
Expand Install Readme 

### ISSUE THREAD

**Issue by RachelWikenMC** [wsp-sag/network_wrangler#175]
For ArcGIS / Cube users - Recommend Install conda by leaving boxes unchecked for advanced options – system path and register anaconda – at least on met council systems, checking these boxes will break our cube and arcgis systems. 

And because of that, directions should mention selecting an anaconda prompt, not a general command prompt, or the conda commands will not be recognized. Also I had to go back and start over with "run anaconda as an administrator" at one point in the install process, even tho I have admin rights to my machine. Was giving me errors on not having permissions to write to system folders.  Have users start with admin anaconda prompt to avoid this issue  

Network Wrangler install steps are unclear. There is a block of “example text” but it is unclear if the user should run that or not. Then there are options for From Clone, From Github. It is unclear what is the recommended path for non-developer users. Make recommended install path for first time users. 

The example box test worked for me, but I wasn’t sure what I was doing or if that was correct option for me or if I needed to also do steps below in the “From Clone” section.  

I got errors on any GIT commands, guessing that needs to be installed first. 

“Test the Install” doesn’t say what you should get from this test or how to know if your test was successful. Need to expand this. It partially ran for me but I was not correctly installed. Highlight what errors might be found and how to fix them. (attaching a couple examples of what I saw) 
![NW error test](https://user-images.githubusercontent.com/46349598/81718888-eb519980-9441-11ea-83de-6f5e993c17d1.PNG)
![pytest results](https://user-images.githubusercontent.com/46349598/81718889-ebea3000-9441-11ea-8fd6-09b717e28d88.PNG)
![Red F](https://user-images.githubusercontent.com/46349598/81718890-ebea3000-9441-11ea-9ec2-b682132c0af6.PNG)

Had lots of issues with the packages, John summarized in “Problem installing lasso #69” on Lasso Issues

cc @JonathanEhrlichMC

**Comment by jhelsel11** [comment]
@RachelWikenMC, in general it is best practice to only elevate permissions on a command prompt as necessary but I will add language that starting the command prompt as an admin may solve some errors.

@e-lo, I'll take a first crack at responding to this in the lasso and network wrangler readmes and let you know when I've done that. I believe some of the issues (e.g. the isntallation test and perhaps the description of the install options will be best addressed by you.

**Comment by jhelsel11** [comment]
@e-lo, I've made a first pass at the network wrangler changes. Will make similar adjustments to lasso and update here.

**Comment by e-lo** [comment]
LGTM!
