### ISSUE TITLE
When deleting links, delete shapes that aren't being used 

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#179]
Shapes exist in network even after they are deleted (see: #176)

**Implementation**

In `delete_roadway_feature_change()` in the `RoadwayNetwork` class:

- [x] write test
- [ ] delete associated shape if not used by another link in the network
- [x] update method documentation to note that this is done

**Comment by kulshresthaa** [comment]
@e-lo How to identify which shapes to delete when a link is deleted?

Say, project card specifies `model_link_id` 477533 to be deleted. 

![image](https://user-images.githubusercontent.com/13478750/84230243-64bfc480-aaa0-11ea-9e09-b4a9eea7cd66.png)

For this link, the `shstGeometryId` is "f4adb182be027662d7457049cac64add". Is this the id that we have to search for `id` in the shapes_df?

In shapes_df there are many shapes with this `id`. Do I delete all? 

![image](https://user-images.githubusercontent.com/13478750/84230444-caac4c00-aaa0-11ea-877c-89bf8c821f74.png)

--

**Comment by kulshresthaa** [comment]
done!

**Comment by e-lo** [comment]
(*putting this note here since this was discussed offline*)
> In shapes_df there are many shapes with this id. Do I delete all?

#182 fixes the problem where shapes don't have a unique id because the shared streets ID is broken up across several links as a result of link-splitting in OSMNX

For this method, we should use the new unique shape ID

**Comment by e-lo** [comment]
@kulshresthaa I have one minor request for using a different (more resilient) pandas method that I put in the commit, then this can be closed!

**Comment by kulshresthaa** [comment]
done!
