### ISSUE TITLE
Add new shapes to shapes table when adding new roadway

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#180]
Shapes for new links don't exist in shapes table (see: #176)

**Implementation**

In `add_new_roadway_feature_change()` in the `RoadwayNetwork` class:

- [ ] write test
- [ ] create a new entry in shapes table
- [ ] add reference to it in links table
- [ ] update method documentation to note that this is done

**Comment by e-lo** [comment]
For new shape geometry IDs, use the method from SharedStreets below.   

Source: https://github.com/sharedstreets/sharedstreets-js/blob/0e6d7de0aee2e9ae3b007d1e45284b06cc241d02/src/index.ts
```javascript
/**
 * Geometry Id
 *
 * @param {Feature<LineString>|Array<Array<number>>} line Line Geometry as a GeoJSON LineString or an Array of Positions Array<<longitude, latitude>>.
 * @returns {string} SharedStreets Geometry Id
 * @example
 * const id = sharedstreets.geometryId([[110, 45], [115, 50], [120, 55]]);
 * id // => "ce9c0ec1472c0a8bab3190ab075e9b21"
 */
export function geometryId(line: Feature<LineString> | LineString | number[][]): string {
  const message = geometryMessage(line);
  return generateHash(message);
}
```

For reference, a python translation of the intersection method is as follows:

```python
import hashlib

message = "Intersection {0:.5f} {0:.5f}".format(long, lat)
if osm_node_id:
        message += " {}".format(osm_node_id)
unhashed = message.encode("utf-8")
hash = hashlib.md5(unhashed).hexdigest()
return hash
```

**Comment by kulshresthaa** [comment]
done! please review @e-lo

**Comment by e-lo** [comment]
Overall LGTM so I will close, but I do have one request on the commit to add another assert.
