### ISSUE TITLE
Method to create unique shape id

### ISSUE THREAD

**Issue by kulshresthaa** [wsp-sag/network_wrangler#182]

**Comment by kulshresthaa** [comment]
@e-lo please review. 

@i-am-sijia see if you can use this method to create "shape_id" in the network (links and shapes)

**Comment by kulshresthaa** [comment]
@i-am-sijia are you able to use the method to create new network with shape_id?

**Comment by e-lo** [comment]
@kulshresthaa  I think only remaining thing is documenting the method

**Comment by kulshresthaa** [comment]
> @kulshresthaa I think only remaining thing is documenting the method

is the added documentation OK?
