### ISSUE TITLE
CRS specification

### ISSUE THREAD

**Issue by i-am-sijia** [wsp-sag/network_wrangler#186]
The following way of specifying standard CRS is not working for me.

https://github.com/wsp-sag/network_wrangler/blob/d18e50bd9f1e900e72ddcbd50623bbba1f0aba9d/network_wrangler/roadwaynetwork.py#L141
https://github.com/wsp-sag/network_wrangler/blob/d18e50bd9f1e900e72ddcbd50623bbba1f0aba9d/network_wrangler/roadwaynetwork.py#L287

It fails when re-projecting to MetCouncil CRS, because the original CRS is not a valid format.

![image](https://user-images.githubusercontent.com/28812722/85880090-72b45b80-b7a9-11ea-9b01-5dc85f36064e.png)

I had to change it to `CRS = {'init': 'epsg:4326'}` to get it working.

**Comment by e-lo** [comment]
@i-am-sijia what is your geopandas and pyproj version? you may need to upgrade

**Comment by i-am-sijia** [comment]
Upgraded packages and worked.
