### ISSUE TITLE
Create default geometry when adding links

### ISSUE THREAD

**Issue by i-am-sijia** [wsp-sag/network_wrangler#187]
It does not seem to create the geometries after applying project cards, and causing @RachelWikenMC issues in plotting.  Test example `
model_road_net.links_df.plot("bike_access")` in https://github.com/wsp-sag/Lasso/blob/master/notebooks/Lasso%20Scenario%20Creation%20Quickstart.ipynb

![image](https://user-images.githubusercontent.com/28812722/85901166-2ed44d00-b7cf-11ea-8412-20c748fbb32c.png)

**Comment by kulshresthaa** [comment]
@i-am-sijia Looking at the current implementation - it does not create geometry for new links when applying "add new roadway" project card. 

+ @e-lo

**Comment by kulshresthaa** [comment]
@e-lo 
Approach - I guess I should revise the `add_new_roadway_feature_change` [method](https://github.com/wsp-sag/network_wrangler/blob/master/network_wrangler/RoadwayNetwork.py#L1286) to first add the nodes. That way new added nodes also exist in the updated nodes_df. Then I should pick the X/Y of A and B nodes of new links from the nodes_df to get the link shape. Right?

**Comment by kulshresthaa** [comment]
@e-lo approach for creating geometry when adding links - add new nodes first so that the nodes_df has updated nodes. Next, for the new links (with missing geometry), get the A and B ids of those links, extract the x/y of those nodes from the nodes_df and then create a geometry of new link in links_df. 

Problem: How do we make sure that if we are adding new links b/w nodes (A/B) which doesn't already exist in the nodes df, then project card should also specify to add those new nodes. Will this be automatically taken care of when creating project card from log?

I was using a [simple roadway add project card](https://github.com/wsp-sag/network_wrangler/blob/develop/examples/stpaul/project_cards/10_simple_roadway_add_change.yml) for testing and was running into error because A/B of the new links doesn't already exist in the nodes and the project card isn't adding those two new nodes.

Let me know. If this is never going to be an issue, then I wouldn't need to consider this case the code.

**Comment by i-am-sijia** [comment]
Yes, new nodes are listed in the project card like this:

```
- category: Add New Roadway
  links:
  - xxx
    xxx
  - xxx
    xxx
  nodes:
  - bike_node: 0
    drive_node: 1
    model_node_id: 354388
    osm_node_id: ''
    walk_node: 0
```

**Comment by e-lo** [comment]
Like @i-am-sijia said, the new nodes are specified in the project card.  However, it seems like the ordering in [`add_new_roadway_feature_change()`](https://github.com/wsp-sag/network_wrangler/blob/a91939ff8b1344b0c2080429b59bbd4f97caf9ed/network_wrangler/RoadwayNetwork.py#L1286) method might be the issue you are encountering? My 10 sec read is that it is adding nodes first and then links but perhaps something else is going on that needs to be addressed.

**Comment by kulshresthaa** [comment]
ordering is ok. method is adding nodes first and then links, which I think is correct. Problem is if there is an inconsistency b/w new links and nodes in the project card. 

The [project card](https://github.com/wsp-sag/network_wrangler/blob/develop/examples/stpaul/project_cards/10_simple_roadway_add_change.yml) is a made up project card (and not from the log). This specifies to add two new links b/w nodes 36622 and 125892 (A/B). Issue is that these two nodes doesn't exist in the nodes data and project card is not specifying to add these two new nodes. 

If the project card was created from log, I assume those two new nodes will also be correctly specified in the project card to add.

**Comment by e-lo** [comment]
Ah! Sounds like that test project card is just outdated and needs to be updated. Please do so. 

@i-am-sijia do you know what the nodes should be? 

While you are at it, can you make sure that the error codes make sense when you try. and add links without pre-requisite nodes? (and address if they don't)

**Comment by kulshresthaa** [comment]
done. please review @e-lo

**Comment by e-lo** [comment]
Just added a handful of comments that I'd like for you to address before I close this:
1. selections before applys since applys are costly
2. `.isin`. rather than `.query` should make code much shorter/legible
3. moving from `.loc` to `.at` for single cells
4. minor ? about "" vs .na

**Comment by kulshresthaa** [comment]
@e-lo I think I have addressed all the comments except the "" vs None for geometry. Please review. 

For geometry, should we change where it gets created to have it as None when missing/empty?

**Comment by e-lo** [comment]
> For geometry, should we change where it gets created to have it as None when missing/empty?

That seems reasonable. Is it really an empty string now? It would seem that it would default to the geopandas None

**Comment by e-lo** [comment]
> @e-lo I think I have addressed all the comments except the "" vs None for geometry. Please review.

Looks great to me – thank you! 

Leaving open to see if you have ideas about "" v None but feel free to close
