### ISSUE TITLE
Change roadway deletion mechanism

### ISSUE THREAD

**Issue by i-am-sijia** [wsp-sag/network_wrangler#190]
Instead of deleting the link, can we just make `drive_access = 0`?  Asking because:

- Deleting the link causes connectivity problem in walk/bike network, when most of the time user actually meant to delete it in the drive network, and was doing so in CUBE.

- It messes up `assign_group` calculation in Lasso, which I couldn't come up with a simple solution.

**Comment by i-am-sijia** [comment]
It seems just need to change this line

https://github.com/wsp-sag/network_wrangler/blob/a91939ff8b1344b0c2080429b59bbd4f97caf9ed/network_wrangler/RoadwayNetwork.py#L1385

**Comment by i-am-sijia** [comment]
Is this ok? @e-lo

**Comment by e-lo** [comment]
My guess is that the primary use case for link deletion is to split a link, in which case the resulting link would provide the walk connectivity.

If a link truly does remain but it is just closed to driving, then we should make a link property change reflecting the drive_access = 0

w.r.t. the `assign_group` calculation in lasso...how is it messing it up?  Whatever our methods are, they should be resilient to removing a link.

**Comment by i-am-sijia** [comment]
I fixed a bug in Lasso in appending `assign_group`.   You are right, the deletion should not affect the `assign_group` calculation.

**Comment by e-lo** [comment]
@i-am-sijia are we good to close this now?
