### ISSUE TITLE
Update managed lane shape creation shape offset to be on right side

### ISSUE THREAD

**Issue by AshishKuls** [wsp-sag/network_wrangler#191]
Right now the create managed lane method offsets managed lane shapes in a single direction (up/right) but it should offset to the right.
Currently the method just offsets the lat/long of GP nodes to create ML nodes and doesn't care that ML link is drawn which side of the GP link.

**Comment by kulshresthaa** [comment]
So, I have made code changes to try and draw the ML correctly in the managed lane network and I would like to visualize the new network to test how the ML looks.

I have a wrangler roadway network object after applying the managed lane project card. What is the easiest way for me to save it as shape file or cube network or something else to be able to open and visualize it?

@e-lo @i-am-sijia @jhelsel11

**Comment by jhelsel11** [comment]
If you output your network as a fixed width format from lasso it will also output a shape file with just the A and B nodes.

It will also output a script like this that will turn the fixed width file into a cube network.: https://github.com/wsp-sag/client_met_council_network/blob/base_network_project_cards/models/batch_file_abm/cube_scripts/make_complete_network_from_fixed_width_file.s

**Comment by jhelsel11** [comment]
(the .s file should show up in the same folder as the fixed width files.)

**Comment by kulshresthaa** [comment]
> If you output your network as a fixed width format from lasso it will also output a shape file with just the A and B nodes.

What are the steps to output network using Lasso?

I don't have Lasso configured on my machine and I would prefer not to spend too much time on configuring and getting it to work. Even if I have to use Lasso, what would be the minimal piece of code for me to use? @i-am-sijia

**Comment by jhelsel11** [comment]
There may be an easier way, but I write the files using this notebook. https://github.com/wsp-sag/Lasso/blob/master/notebooks/Lasso%20Scenario%20Creation%20Quickstart.ipynb

(You would need to change file paths because we recently reorganized the met council repo location for project cards.)

**Comment by i-am-sijia** [comment]
> I don't have Lasso configured on my machine and I would prefer not to spend too much time on configuring and getting it to work.

If you don't want to use Lasso, you can append geometry from shape.geojson to link.json and write out a geojson file.

If you use Lasso, take a look at the [test_roadway.py](https://github.com/wsp-sag/Lasso/blob/develop/tests/test_roadway.py), you can pytest method [test_write_roadway_as_shape](https://github.com/wsp-sag/Lasso/blob/b4deb05e751844ebfce0aa980f0a1e685ddd61ad/tests/test_roadway.py#L175), or [test_write-cube_roadway](https://github.com/wsp-sag/Lasso/blob/b4deb05e751844ebfce0aa980f0a1e685ddd61ad/tests/test_roadway.py#L157)

@kulshresthaa

**Comment by e-lo** [comment]
@kulshresthaa Looks good overall but I have some requests/questions noted here and below: https://github.com/wsp-sag/network_wrangler/commit/cda9f3c8219008aa5ad51a25ca0f819fad8c8af2

- [ ] docstrings for new functions
- [ ] assert statements for unit tests 
- [ ] shouldn't have project cards labeled `_ak` 
- [ ] add geodesic to requirements

btw - is geodesic hard. to install?

**Comment by kulshresthaa** [comment]
@DavidOry @e-lo adding 90 degrees to the bearing does create the ML links and access/egress nicely. I guess I can now say with some confidence that it is working :)

![image](https://user-images.githubusercontent.com/13478750/90691305-f9286f00-e227-11ea-84df-c18d2e7babb6.png)

.

![image](https://user-images.githubusercontent.com/13478750/90692774-8a004a00-e22a-11ea-9b83-fb1ab093f83a.png)

**Comment by kulshresthaa** [comment]
> @kulshresthaa Looks good overall but I have some requests/questions noted here and below: [cda9f3c](https://github.com/wsp-sag/network_wrangler/commit/cda9f3c8219008aa5ad51a25ca0f819fad8c8af2)
> 
> * [ ]  docstrings for new functions
> * [ ]  assert statements for unit tests
> * [ ]  shouldn't have project cards labeled `_ak`
> * [ ]  add geodesic to requirements
> 
> Qs:
> 
> * is geodesic hard to install?
> * do you need to do this for shapes as well?  We want to offset the "true shape" rather than the AB shape...


@e-lo Can you confirm if all your comments for this have been addressed in the last [commit](https://github.com/wsp-sag/network_wrangler/commit/7d7744ddde9d12bbfd67a75d2e453c91e3e588c6)

Do you see `geographiclib` package in your conda list? I dont recall if I had to separately install `geographiclib` or was it already there.

**Comment by e-lo** [comment]
Will allow you to offset either way now in params: `ML_OFFSET_METERS = -5`
