### ISSUE TITLE
long lists of model link ids cause an error in project cards

### ISSUE THREAD

**Issue by jhelsel11** [wsp-sag/network_wrangler#194]
I tried to apply the following project card to a scenario.

https://github.com/wsp-sag/client_met_council_network/blob/base_network_project_cards/project_cards/year_2018_corrections_assign_group.yml

Doing so created a recursion error that appears to be due to having too many conditions in a filter. 

Can you let me know what the implicit limit is for the number of links that can be changed in a call? Or can you adjust the wrangler code so that there is no limit?

CC'ing @i-am-sijia, since she also saw the errors.

**Comment by e-lo** [comment]
@jhelsel11 can you post the traceback? (generally necessary for tracking down bugs)

It certainly isn't supposed to have any implicit limit from our perspective but the method we used may have one we aren't aware of.

**Comment by i-am-sijia** [comment]
The recursion error happened in this query:
https://github.com/wsp-sag/network_wrangler/blob/f4d591a4672bab9fc603826ec62040bf8711fd5c/network_wrangler/roadwaynetwork.py#L851-L853

**Comment by jhelsel11** [comment]
@e-lo, here's the result from running too many changes at once: https://github.com/wsp-sag/Lasso/blob/develop/notebooks/make_scenario_I394E_managed_lanes.ipynb

**Comment by jhelsel11** [comment]
or, see the commit here: https://github.com/wsp-sag/Lasso/commit/0a04fee0d59489ee034db75489b33d6518fc980c
