### ISSUE TITLE
osmnx dependency errors with numpy and pyproj

### ISSUE THREAD

**Issue by JonathanEhrlichMC** [wsp-sag/network_wrangler#195]
Getting following error when installing:

ERROR: osmnx 0.15.1 has requirement numpy>=1.18, but you'll have numpy 1.17.4 which is incompatible.
ERROR: osmnx 0.15.1 has requirement pyproj>=2.6, but you'll have pyproj 2.4.2.post1 which is incompatible.

**Comment by e-lo** [comment]
It seems like you had previous versions installed in this environment? 

I think running [`conda update`](https://docs.conda.io/projects/conda/en/latest/commands/update.html) before running a pip install should do the trick.  

It is annoying that osmnx is requiring such recent versions, though.

**Comment by e-lo** [comment]
Any luck on this @JonathanEhrlichMC ?

**Comment by JonathanEhrlichMC** [comment]
Updating numpy seems to have solved it. I still have pyproj 2.4.2.post1- when I try to update I get:

PackageNotInstalledError: Package is not installed in prefix.
  prefix: C:\Users\ehrlicjn\AppData\Local\Continuum\anaconda3\envs\lasso
  package name: pyproj

**Comment by JonathanEhrlichMC** [comment]
I went ahead and installed pyproj from scratch in lasso and now it has a recent version. Strange. In any case, the error is gone.
