### ISSUE TITLE
process project cards with python changes

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#199]
In order to accommodate large-scale network changes efficiently which can be accomplished via the network wrangler API while **also** retaining the important metadata and scenario-building functionality, network wrangler should be able to process project card that contain the YAML front-matter metadata followed by python content which completes the editing.

This type of approach is similar to how Vue has .vue files, or jekyll processes markdown files.

Suggested format as follows:

`my_awesome_project.wrangler`
```python
---
project: my awesome project
prerequisites:
category: roadway
---

links_df.loc[links_df['lanes'] == 4, 'lanes'] = 12

```

Implemented for:
- [x] Project Card Read
- [x] Roadway Network Apply
- [ ] Transit Network Apply

**Comment by DavidOry** [comment]
fyi @lmz

**Comment by e-lo** [comment]
I did over half of the work (project card read, roadway network apply) - anybody want to take on transit ? :-)
