### ISSUE TITLE
Parameterize wrangler methods to allow for different parameters for different agencies.

### ISSUE THREAD

**Issue by i-am-sijia** [wsp-sag/network_wrangler#229]
Wrangler attributes such as [MANAGED_LANES_NODE_ID_SCALAR](https://github.com/wsp-sag/network_wrangler/blob/b7395c9c197c3f311dd12769882bff676be9f66b/network_wrangler/roadwaynetwork.py#L158) should be flexible and subject to MPO's choice, instead of hard coded in the source scripts.  The current setting does not work for MTC network.

**Comment by e-lo** [comment]
Can I tackle this one? also working on refactoring lasso parameters.

**Comment by e-lo** [comment]
Based on group discussion, we will:

1. store "best" default parameters for each class; stored at class-level
2. update methods to be able to override default parameters

**Comment by e-lo** [comment]
This is implemented as wrangler parameters.
