### ISSUE TITLE
[BUG] Error when applying project cards on attributes that are dictionaries

### ISSUE THREAD

**Issue by AshishKuls** [wsp-sag/network_wrangler#234]
## Describe the bug
When the user apply a parallel managed lane project card and then apply another project card on the wrangler network, it throws an error. 

The reason is that when a managed lane project card is applied, one or more attributes become dictionary segmented by the time of day for certain roadway segments, and then any other change for those attributes wouldn't be possible on the same roadway segments within the wrangler network/environment. 

## To Reproduce
An example is [here](https://github.com/wsp-sag/network_wrangler/blob/develop/notebook/change-functionality-bug.ipynb) - this applies a parallel managed lane card and a roadway property change project card in sequence: 

### Failing tests
- [ ] No applicable test failed, need to create.

### Thoughts on resolution
Two approaches were discussed as a workaround solution: 
* After applying the managed lane project card on wrangler network, export it out as a model network (which will separate out the parallel managed lane) and then read the network back into wrangler to apply any other changes 

* something with writing out .wrangler file.

**Comment by kulshresthaa** [comment]
@DavidOry Could you please update the second possible approach - doing something with the .wrangler file?

**Comment by DavidOry** [comment]
Note this issue is broader than post managed lanes card application, as any attribute can be a dictionary.

**Comment by e-lo** [comment]
Now works fine in v1 branch: https://github.com/wsp-sag/network_wrangler/pull/327
