### ISSUE TITLE
[BUG] Duplicated Nodes Created If The Parent Node Is Referenced In More Than One Managed Lane Card

### ISSUE THREAD

**Issue by i-am-sijia** [wsp-sag/network_wrangler#256]
## Describe the bug
When there is a managed lane project card for Link(u,v), and another managed lane project card for Link(u,w), Node(u) will have two offset dummy nodes created with the same scalar, resulting in non-unique nodes.

### Thoughts on resolution
When applying a managed lane project card, check if a node already has a dummy node created in the database by other project cards.  And maybe the same should be checked for links?

**Comment by kulshresthaa** [comment]
@e-lo I push the fix for this issue to `develop` or `generic_agency` branch?

**Comment by e-lo** [comment]
`generic agency` is fine

**Comment by kulshresthaa** [comment]
@i-am-sijia Could you please test this fix using the setup you previously used where the bug was identified?

**Comment by i-am-sijia** [comment]
@kulshresthaa It works! No duplicate node or link IDs any more.  Thanks.
