### ISSUE TITLE
offset_lat_lon is not a defined method or variable.

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#257]
@kulshresthaa  - wondering if the method name just got updated somewhere but not here?

https://github.com/wsp-sag/network_wrangler/blob/c70a731e74be20fef42f85c2c847e30a320eee7c/network_wrangler/roadwaynetwork.py#L2298-L2306

**Comment by kulshresthaa** [comment]
`_update_location_reference` method is not used anymore, you can take it out. 

https://github.com/wsp-sag/network_wrangler/blob/c70a731e74be20fef42f85c2c847e30a320eee7c/network_wrangler/roadwaynetwork.py#L2313-L2316

**Comment by e-lo** [comment]
Addressed in #310
