### ISSUE TITLE
failed to apply transit routing project cards in scenario

### ISSUE THREAD

**Issue by i-am-sijia** [wsp-sag/network_wrangler#261]
## Describe the bug
This the first time applying real transit routing project cards in a scenario set up, getting some errors such as
```python 
z:\data\users\sijia\mtc\github\network_wrangler\network_wrangler\transitnetwork.py in select_transit_features(self, selection)
    721                 else:
    722                     WranglerLogger.error("Selection not supported %s", key)
--> 723                     raise ValueError
    724 
    725         # Check that there is at least one trip in trips table or raise error

ValueError: 
```
### Example project card 
[example](https://github.com/BayAreaMetro/travel-model-two-networks/blob/a5100ce62e43018822bb06f07702778089c53d10/project_cards/SamTrans-route-393-edits.yml)

### to do:

- [x] route selection by `start_time` and `end_time` is not read in correctly, need to correct.
- [ ] `start_time` and `end_time` are not in trips, they need to be joined from frequencies
- [ ] check when new stops being added
- [ ] etc

**Comment by e-lo** [comment]
Pretty sure this is now fixed.
