### ISSUE TITLE
[FEATURE] Add new transit

### ISSUE THREAD

**Issue by i-am-sijia** [wsp-sag/network_wrangler#264]
### User Story
There seems to be no "Add New Transit" category

https://github.com/wsp-sag/network_wrangler/blob/242220f713f3579b62b9d0624d4b970d3363a916/network_wrangler/projectcard.py#L24-L36

, and we can't use the existing category "Transit Service Property Change" because it returns error if the service is not already in the network:

https://github.com/wsp-sag/network_wrangler/blob/242220f713f3579b62b9d0624d4b970d3363a916/network_wrangler/transitnetwork.py#L732-L735

### Priority 
High

### Level of Effort
Medium to high

### Resolution Ideas
Need to develop the related methods

### Project
*Is there a funder or project associated with this feature?*

I was hoping to use project card to add some missing transit for MTC.
@e-lo, @DavidOry  Am I right "add new transit service" was not developed?

**Comment by e-lo** [comment]
This was completed.
