### ISSUE TITLE
[BUG]  Prerequisite requirement failing when prerequisite project is added at same time

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#269]
## Describe the bug
Prerequisite requirement failing when prerequisite project is added at same time.

Bug fix approver: @i-am-sijia

## To Reproduce
@i-am-sijia - please add

### Failing tests
@i-am-sijia please add
- [ ] No applicable test failed, need to create.
- [ ] 

### Thoughts on resolution
@kulshresthaa

**Comment by kulshresthaa** [comment]
@i-am-sijia Do you have steps for me to understand what exactly you were doing in order for me to replicate this issue?

**Comment by kulshresthaa** [comment]
@i-am-sijia @DavidOry I tested this prerequisite requirement and it worked as expected and had no issues. We can discuss it on the call next week.
