### ISSUE TITLE
[BUG] Case issue with "Project" key in project card

### ISSUE THREAD

**Issue by AshishKuls** [wsp-sag/network_wrangler#273]
## Describe the bug
case for `project` key from the project card isn't used in a consistent manner, causing the problems 

For example, `prerequisite` dictionary stores the project keys as read from the project card (without converting the case to lower)

https://github.com/wsp-sag/network_wrangler/blob/master/network_wrangler/scenario.py#L133
https://github.com/wsp-sag/network_wrangler/blob/master/network_wrangler/scenario.py#L137

and then this line would be a problem, as the project here is lowercase but the key in prerequisite is not. 
https://github.com/wsp-sag/network_wrangler/blob/master/network_wrangler/scenario.py#L460

Based on these two project cards:
![image](https://user-images.githubusercontent.com/13478750/118730099-e610f280-b7eb-11eb-8104-6f64bf302bb2.png)
![image](https://user-images.githubusercontent.com/13478750/118730134-f6c16880-b7eb-11eb-9e01-be63fc9457e0.png)

prerequisite dictionary will be :
`{'SFMTA Route N-JUDAH': ['move street rail to street connector links']}`

and `prerequisite.get('sfmta route n-judah')` wouldn't return anything [here](https://github.com/wsp-sag/network_wrangler/blob/master/network_wrangler/scenario.py#L460)

### Thoughts on resolution
use card.project to card.project.lower() throughout and keep it consistent (lowercase).

**Comment by e-lo** [comment]
Discussed solution:

- [ ] remove `.lower()` statements for `self.project` 
- [ ] make sure it gives you a warning if you list pre-reqs that aren't found

**Comment by e-lo** [comment]
This should be fine now that project card is using Pydantic to normalize it and network wrangler is using that consistently.
