### ISSUE TITLE
[FEATURE] Project cards should log their own filename

### ISSUE THREAD

**Issue by lmz** [wsp-sag/network_wrangler#274]
### User Story
*As a modeler building networks and applying project cards, my logs show things like this:

> 2022-01-13 16:19:08, INFO: Applying Year 2015 Modify Facility Type to Ramp shape incorrect

What project card is that referring to?  I'd rather know what the filename is called than have to search my project cards for that text.  What if multiple cards have the same description?  (or is that a title?).  

I think it would be more useful to say something like:

> 2022-01-13 16:19:08, INFO: Applying [year_2015_roadway_property_change_should_be_ramp_shape_incorrect.yml]: Applying Year 2015 Modify Facility Type to Ramp shape incorrect

### Priority 

To me?  High ;)

### Level of Effort

low

### Project
MTC

### Who should be involved?
Implementer: 
Commenters: 
Users: 
Reviewers: 

### Risk
*Will this potentially break anything?*

#### Tests
*What are relevant tests or what tests need to be created in order to determine that this issue is complete?*

**Comment by e-lo** [comment]
I agree with your proposed logging change and think this makes sense.

**Comment by lmz** [comment]
I'm happy to do this (to get familiar with the contributing process) although it looks like I don't think I have permissions to assign the issue.  Would I make a pull request to the develop branch?  (Or create a feature branch...?  The change seems a bit minor for that)

**Comment by e-lo** [comment]
Make a feature branch that you then merge into develop as your PR...the
tests and such will then run on the PR

**Comment by e-lo** [comment]
@lmz can you PR that to this repo plz?

**Comment by e-lo** [comment]
Also fixed in v1 now.
