### ISSUE TITLE
[BUG] Document and check for RoadwayNetwork.shape_foreign_key

### ISSUE THREAD

**Issue by lmz** [wsp-sag/network_wrangler#276]
## Describe the bug

I was trying to use a [script](https://github.com/BayAreaMetro/travel-model-two-networks/blob/ad5f24eb3dad798be4e4d9aa433bb9bcca578357/notebooks/02-correct-network-errors.ipynb) that errored out when applying a project card that added new roadway links.  On [digging](https://app.asana.com/0/0/1201662144568397/f), I found it was because the `RoadwayNetwork.shape_foreign_key` was being used to access columns in both the `shapes_df` and `links_df`: https://github.com/wsp-sag/network_wrangler/blob/6ed22407594e4e923f578d56455cb254058933ec/network_wrangler/roadwaynetwork.py#L1727-L1732

I think this is ok but it should be documented clearly and also fail earlier by checking that `links_df` has the column, in the same way that the check is done for `shapes_df`: https://github.com/wsp-sag/network_wrangler/blob/6ed22407594e4e923f578d56455cb254058933ec/network_wrangler/roadwaynetwork.py#L507-L512

### Status

- [x] Defined
- [x] Planned
- [x] Implemented
- [x] Tested

## To Reproduce
1. Create a network with a shape_foreign_key that exists in `shapes_df` but not `links_df`
2. Apply a project card that creates roadway links

### Failing tests
- [ ] No applicable test failed, need to create.
- [ ] 

### Environment

Operating system:
Context (conda, jupyter, etc):
Environment (e.g. output from `conda list`):

**Comment by e-lo** [comment]
Resolved in v1.0 release candidate by being much more rigorous about data models for networks including checking for FKs
