### ISSUE TITLE
[FEATURE] Add Network Validator

### ISSUE THREAD

**Issue by DavidOry** [wsp-sag/network_wrangler#285]
### User Story
A user uses [`Ranch`](https://github.com/wsp-sag/Ranch) to create travel model networks. The user then wants to check if the networks meet the requirements to use Network Wrangler. Ideally, a validator would be in place to check that the networks have the required attributes.

### Status

- [x] Defined
- [x] Planned
- [x] Implemented
- [x] Tested

### Priority 
Low

### Level of Effort
Low

### Resolution Ideas
Update, as needed, the [roadway schemas](https://github.com/wsp-sag/network_wrangler/tree/master/network_wrangler/schemas). Confirm that other GTFS validators ([example](https://github.com/MobilityData/gtfs-validator)). Bundle tools together in a validator method (should this be a separate project?)  

### Project
No

### Who should be involved?
Implementer: @e-lo 
Commenters: @DavidOry 
Users: @lmz
Reviewers: @i-am-sijia 

### Risk
Will require on-going maintenance.

#### Tests
Demonstrate successful and unsuccessful validation efforts.

**Comment by e-lo** [comment]
Addressed in v1.0
