### ISSUE TITLE
[FEATURE] setupLogging call in __init__.py is overly prescriptive

### ISSUE THREAD

**Issue by lmz** [wsp-sag/network_wrangler#286]
### User Story
*As a modeler creating networks, I would prefer to explicitly setup logging rather than automatically in network_wrangler's `__init__.py`*:

https://github.com/wsp-sag/network_wrangler/blob/6ed22407594e4e923f578d56455cb254058933ec/network_wrangler/__init__.py#L40-L46

This is because we find it most useful to have the logs be relevant to what is being done, e.g.
* `build_pipline_network_[date-time].log`
* `apply_projects_[date-time].log`
* `convert_standard_network_to_geopackage_[date-time].log` 
etc

I believe that having this line on the import means that even if we call `setupLogging()` later to create our own log file, we'll now have two, because the import will create one:

```
(tm2_network_dev) PS C:\temp\logtest> python
Python 3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import network_wrangler
>>> network_wrangler.setupLogging(log_filename="custom_log_test.log")
>>> network_wrangler.WranglerLogger.info("This is a test")
2022-03-24 10:30:35, INFO: This is a test
>>> quit()
(tm2_network_dev) PS C:\temp\logtest> ls


    Directory: C:\temp\logtest


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        3/24/2022  10:30 AM             43 custom_log_test.log
-a----        3/24/2022  10:30 AM             43 network_wrangler_2022_03_24__10_30_04.log


(tm2_network_dev) PS C:\temp\logtest> type .\custom_log_test.log
2022-03-24 10:30:35, INFO: This is a test
(tm2_network_dev) PS C:\temp\logtest> type .\network_wrangler_2022_03_24__10_30_04.log
2022-03-24 10:30:35, INFO: This is a test
```

### Priority 
High
### Level of Effort
Low
### Resolution Ideas
I would prefer to remove this line from `__init__.py` and let the user call `setupLogging()`.  
Ideally, we could call this later if the logger is invoked without having being setup -- is that possible?

### Project
*Is there a funder or project associated with this feature?*
MTC
### Who should be involved?
Implementer:  @yuqiww
Commenters: 
Users: 
Reviewers: 

### Risk
*Will this potentially break anything?*
I don't think so, especially if we could setup logging later if needed as described above.

#### Tests
*What are relevant tests or what tests need to be created in order to determine that this issue is complete?*
We could create a test to verify that both situations work as intended -- if the user sets up a logger explicitly and if the user does not.

**Comment by e-lo** [comment]
@yuqiww can you submit a PR into this repository with this change?  I'm happy to merge.

Suggested additions:

- update notebooks to call setuplogging
- update documentation

**Comment by yuqiww** [comment]
> @yuqiww can you submit a PR into this repository with this change? I'm happy to merge.
> 
> Suggested additions:
> 
> * update notebooks to call setuplogging
> * update documentation

@e-lo: 

- re notebooks, were you referring to [these notebooks](https://github.com/BayAreaMetro/network_wrangler/tree/generic_agency/notebook)?  
- re documentation, it seems appropriate to add sample code to "[Usage](https://github.com/BayAreaMetro/network_wrangler/tree/generic_agency#usage)". Are there other places you were thinking about?

**Comment by e-lo** [comment]
Addressed in merged PR.
