### ISSUE TITLE
[PERFORMANCE] - Slow to apply projects

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#288]
Taking 3-4 minutes to add a single link on full MetCouncil Network

RAM only at ~60%.

This shouldn't be taking so long - the process should be parallel.

Investigate with timed INFO logs. 

Potentially add instrumentation / continuous benchmarking using [pytest-benchmark](https://pytest-benchmark.readthedocs.io/en/latest/index.html)

**Comment by i-am-sijia** [comment]
@e-lo the new network wrangler is taking longer to apply project cards. E.g., to apply this roadway property change card: https://github.com/Metropolitan-Council/project_card_registry/blob/Test1_converted_project_cards/projects/BaseCorrections/year_2018_corrections_assign_group.yml. It's been running for 15 mins and still not finished. It is probably doing a lot of caching and validation?

**Comment by i-am-sijia** [comment]
For example, perhaps we should skip the the `DataFrame[RoadLinksTable]` validations in the input and output of this function, when we have a long list of project cards to apply. Just validate in the first and last project card?

https://github.com/wsp-sag/network_wrangler/blob/b7b3b9196c662c74331a3412d9831e7bce2407bd/network_wrangler/roadway/links/edit.py#L242-L261

**Comment by e-lo** [comment]
I'm planning on running a performance profiler this afternoon after I resolve the other issues to see where it is taking all the time...

**Comment by e-lo** [comment]
I think we are good here for now but let's re-open specific issues as they arise.
