### ISSUE TITLE
Managed Lane Project Card Consumption

### ISSUE THREAD

**Issue by DavidOry** [wsp-sag/network_wrangler#29]
Update project card read, [project card schema](https://github.com/wsp-sag/network_wrangler/blob/master/schemas/project_card.json), and validation methods to adhere to updates to the project card design.

https://jsonschema.net/ is a useful resource for updating the schema

**Comment by e-lo** [comment]
Per our stand-up today, when consuming time of day for managed lane project card, should invoke the parse time spans utility to convert the tuple of strings to tuple of seconds from midnight similar to how the transitNetwork now uses it.

https://github.com/wsp-sag/network_wrangler/blob/19cedb8ffba413610f0bd57a03da572edbe3b67e/network_wrangler/Utils.py#L70-L80

https://github.com/wsp-sag/network_wrangler/blob/19cedb8ffba413610f0bd57a03da572edbe3b67e/network_wrangler/TransitNetwork.py#L161

**Comment by e-lo** [comment]
Fixed in https://github.com/wsp-sag/network_wrangler/pull/68
