### ISSUE TITLE
[CHORE] Switch from Travis to GH Actions

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#291]
As a developer, I'd like to use a CI service which more tightly integrates with other things I'd like to do, like publish documentation.

The necessary migration from travis.org --> travis.com provides an opportunity to do so.

**Comment by DavidOry** [comment]
@e-lo
If we move to GitHub Actions, it would be nice to use [Docker as the runtime environment](https://docs.github.com/en/actions/creating-actions/dockerfile-support-for-github-actions) (perhaps a separate Docker image for tests and documentation) when running the Actions. This would be a nice nudge to (a) keep the Dockerfile up to date and (b) use the same Python environment in testing that we will in deployment.

**Comment by e-lo** [comment]
Completed!
