### ISSUE TITLE
[FEATURE] Object Mutability Consistency

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#308]
### User Story
*As a user I'd like to have a consistent expectation about if I am modifying an object in-place or creating a mutated copy.*

### Status

- [x] Defined
- [x] Planned
- [x] Implemented
- [x] Tested

### Context

Right now, there is are public methods in roadway and transit network objects that:

- mutate the object in-place
- return the mutated object
- have an option to do either

This inconsistency in the API has caused lots of confusion and bugs.

### Resolution Ideas

Add and implement the following design principle:

- Public methods of the transit and roadway networks should always return a copied, mutated form of the network object

### Priority 
High

### Level of Effort
Low

### Project
*Is there a funder or project associated with this feature?*

### Who should be involved?
Implementer: 
Commenters: 
Users: 
Reviewers: 

### Risk
*Will this potentially break anything?*

#### Tests
*What are relevant tests or what tests need to be created in order to determine that this issue is complete?*

**Comment by e-lo** [comment]
Update: will test performance of deep copy on a real-size network to evaluate if this is an ok default.

**Comment by DavidOry** [comment]
Well that's encouraging. Perhaps we create another issue to remind us to test this once version 1 is released, but for now move ahead with your original plan?

**Comment by e-lo** [comment]
Fixed in https://github.com/wsp-sag/network_wrangler/pull/327
