### ISSUE TITLE
Validate Roadway Schema

### ISSUE THREAD

**Issue by DavidOry** [wsp-sag/network_wrangler#32]
* Use #31 to validate the input roadway
* Validator method

**Comment by josiekre** [comment]
I think this is a duplicate of #40, right?

**Comment by e-lo** [comment]
yes. i'll delete 40

**Comment by e-lo** [comment]
Completed based on schema, but could add other validations in future.

**Comment by e-lo** [comment]
This is done but will need to be updated as we evolve the network standard.
