### ISSUE TITLE
[BUG] Dependency sort does not work properly when a project is the repreq for more than one other projects

### ISSUE THREAD

**Issue by i-am-sijia** [wsp-sag/network_wrangler#341]
## Describe the bug
From Rachel:

My 2050 build scenario is still spinning but I’m noticing an issue with the project card order that is ignoring pre-reqs. 

I have two managed lanes projects (94 NB and 94 SB) that use links created in another project card (mn252 hwy conversion). I set this highway project as a pre-req for both managed lanes. But 94 NB Mnpass ran before the mn252 card, ignoring the pre-req. The 94SB card ran after, correctly following the prereq. The pre-reqs look identical, so I’m confused why this might be. Any idea?  I’m hoping when I review outputs tomorrow this won’t be an issue but based on this output message I’m guessing my NB lane will be missing segments. 

Full output copied below, important sections highlighted 
![image](https://github.com/wsp-sag/network_wrangler/assets/28812722/263d083e-c2e4-419d-bc2a-74d5f92ec063)

## To Reproduce
1. Sijia reproduced Rachel's error by using [this notebook](https://wsponlinenam.sharepoint.com/:u:/r/Sites/US-MetCNetworkWrangler/Shared%20Documents/Task%204%20Use%20Cases/notebooks/[test-highway-dependency.ipynb](https://wsponlinenam.sharepoint.com/:u:/r/Sites/US-MetCNetworkWrangler/Shared%20Documents/Task%204%20Use%20Cases/notebooks/test-highway-dependency.ipynb?csf=1&web=1&e=lZjWmF)?csf=1&web=1&e=lZjWmF)

### Triggering line of code
https://github.com/wsp-sag/network_wrangler/blob/8fa7698d6e9d2348bb537a25dfa63fd61bb43cc3/network_wrangler/scenario.py#L473-L486

### Thoughts on resolution
The sorting pre-req code is not treat more than one dependent card properly. Instead of overwriting the `adjacent_list`, it should append.  The error is on line 481.

### Environment

Operating system: Win64
Context (conda, jupyter, etc):
Environment (e.g. output from `conda list`):
Lasso: develop_with_ranch
Wrangler: develop_with_ranch

fyi: @RachelWikenMC

**Comment by i-am-sijia** [comment]
I tested the code fix locally and it's working. We will close this issue once Rachel confirms this is working for her.

**Comment by e-lo** [comment]
Implemented in selection-refactor branch as https://github.com/wsp-sag/network_wrangler/commit/5bf40e663ff893ce9e3ba4b4ebdd36a993f532c5
