### ISSUE TITLE
Data Model: `stop_id` == `model_node_id`

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#354]
## Problem to solve / Question Asked

Transit datasets should validate to GTFS (or should they?)

## Context

At the outset, we added `model_node_id` to `stops.txt` in order to crosswalk between the roadway network and the transit stops, which in GTFS are off-roadway nodes where a person actually waits for the bus (i.e. a specific corner of an intersection). 

Because there are sometimes many `stop_ids` for each `model_node_id` it became ambiguous as to *which* `stop_id` should be added to a new routing, so , we added `trip_id` to `stops.txt` as a way to distinguish the fact that some trips stop at one stop vs another for the same roadway node, thus giving `stops.txt` a dual-field primary key of `stop_id`, `trip_id`.  

## Issue

- Altering the primary key of `stops.txt` makes our transit data break very basic GTFS validation rules; thus making it impossible to leverage any existing GTFS infrastructure.
- Having a dual-field primary key is more onerous and hard to keep track of.
- Larger datasets will see `stops.txt` "blow up" w.r.t. size.
- Data associated with the actual stop is duplicated

### 1. Keep dual PK

Pros: 

- lasso and network creation currently set up this way
- can keep gtfs-defined concept of what a stop_id is

Cons:

- wrangler 1 needs a lot of editing for routing algorithm (although can leverage <1.0 wrangler logic)
- ❌ Invalid GTFS; wont (ever) be able to use GTFS tooling
- data model overly large

### 2. Migrate back to `stop_id` being PK and `model_node_id` as an added field.

Pros:

- can keep gtfs-defined concept of what a stop_id is
- Will be valid GTFS; can use GTFS tooling

Cons:

-  ❌  no guarantee of choosing correct `stop_id` consistently when editing which could cause networks to look inconsistent when they are effectively the same w.r.t. the model.
-  could be picking a `stop_id` that is for the wrong direction of travel

### 3. Make `stop_id` the `model_node_id` and keep the o.g. GTFS stop_id as an added FYI field.

Pros:

- Will be valid GTFS. Can use GTFS tooling
- Much cleaner merges/joins than are currently necessary to do routing changes
- Efficient data model

Cons:

- Requires retooling (in this case, removing rather than adding complexity)
- stop_id's wont be same as o.g. GTFS (can be FYI's though)

## Stakeholder Thoughts 

*Please comment below and I can fill out this table (or you can)*

❌ - dealbreaker
✅ - preferred option
☑️  - could live with it

Stakeholder | Option 1 | Option 2 | Option 3 
----- | ----- | ----- | -----
@RachelWikenMC |  ❔  |  ❔  |  ❔  |  
@lmz  |  ❔  |  ❔  |  ❔  |  
@gregerhardt  |  ❔  |  ❔  |  ❔  |  
@i-am-sijia  |  ☑️  |  ❌  |  ✅  |  
@e-lo  |  ❌  |  ❔  |  ✅  |  
@DavidOry  |  ☑️  |  ☑️  |  ✅  |

**Comment by DavidOry** [comment]
I can live with anything, but it seem Option 3 is the obvious winner here. We should note that this happens because when we route the buses using the Ranch algorithm, we may route two buses that go through the same `stop_id` may be mapped to different `model_node_id`s. The algorithm does not require each route to travel through each stop -- there is an error tolerance.

**Comment by i-am-sijia** [comment]
Just to clarify - 

Option 1:
stop_id|model_node_id|trip_id|
----|----|----|
1234|100001|route_1_southbound_trip1|
1235|100001|route_1_northbound_trip1|
1235|200002|route_2_westbound_trip1|
7890|100001|route_7_eastbound_trip1|

Option 3: 
stop_id|stop_id_GTFS|
----|----|
100001|1234,1235|
200002|1235,7890|

**Comment by e-lo** [comment]
Implementing Option 3 with @yueshuaing doing the data changes and @e-lo doing code simplification.
