### ISSUE TITLE
[FEATURE] Split mixed-type lanes and price on read to `lanes` and `sc_lanes` in `read_links` / add option to combine into single value for `write_links`

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#359]
### User Story
*As a user of previous network standard versions,  I'd like to be able to read and write to those versions*

### Current data model
<variable_name>: <default_value>
`sc_<variable name>`: [<scoped_value>, <scoped_value>, ...]  

Where `scoped_value` is an object with:

- `set` or `change`: <property_value>
- `timespan` and or `category`

Where  `timespan` : ['HH:MM':'HH:MM']

### Previous data model
<variable_name>: <value> (if doesn't vary by category or timespan)
<variable_name>: {
'default': <default_value>
'timeofday': [<scoped_value>, <scoped_value>, ...]
}

where `scoped_value` is an object with:

- "category" and/or "time"
" value": <value for scoped item>

where "time" is tuple(integer)
      time span as seconds from midnight

**Comment by e-lo** [comment]
@yueshuaing this should be working in latest commit. 
See tests in bottom of `tests/test_roadway/test_io.py` and confirm this is the functionality we need.

**Comment by yueshuaing** [comment]
The `read_links` is working, but the `write_links` is having some issue as noted in issue https://github.com/wsp-sag/network_wrangler/issues/367#

**Comment by e-lo** [comment]
@yueshuaing is this all addressed now and can this be closed?
