### ISSUE TITLE
[FEATURE] ML node ids should be 950,000+

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#361]

**Comment by e-lo** [comment]
@i-am-sijia what about `model_link_id`s?

**Comment by e-lo** [comment]
@yueshuaing can you review my implementation of this in the above commit and make sure it is satisfactory?

**Comment by yueshuaing** [comment]
> @yueshuaing can you review my implementation of this in the above commit and make sure it is satisfactory?
The 950,000-999,999 only applies to node ids. There are links within 950,000-999,999 already in the network

**Comment by e-lo** [comment]
> There are links within 950,000-999,999 already in the network

Ok - what would be a good default range for them?

**Comment by yueshuaing** [comment]
> > There are links within 950,000-999,999 already in the network
> 
> Ok - what would be a good default range for them?

I don't think Cube has the limit on model_link_ids, we can still use the scalar method

**Comment by i-am-sijia** [comment]
> @i-am-sijia what about `model_link_id`s?

As Yue mentioned, we will continue using the link scalar for ML link ids.

**Comment by e-lo** [comment]
i think we should be consistent in creating IDs.  If we have a range explicitly specified for nodes we can do same with links. This is what I implemented.

**Comment by i-am-sijia** [comment]
> i think we should be consistent in creating IDs. If we have a range explicitly specified for nodes we can do same with links. This is what I implemented.

Met Council uses the link scalar to associate ML with GP in their model scripts and post processing steps. That's why they want to keep the link scalar.

**Comment by e-lo** [comment]
@yueshuaing please add a test to make sure the changes in #379 work for you for scalar link ids.  I only tested at micro level. Would be good to add an actual test in test_model_roadway.py
