### ISSUE TITLE
Default to all modes when searching for links to delete

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#364]
## Problem

@yueshuaing uncovered an issue where, because the default search mode is "drive" that unless we specify that we want it to be "all" or add other modes in the facility search in the project card, network deletion will not find links from a link id when they are sidewalks, etc.

## Proposed Solution

When running a facility query for a roadway deletion project, default to "all" modes.

**Comment by e-lo** [comment]
@yueshuaing - LMK if this looks good and I can easily implement today.

**Comment by yueshuaing** [comment]
> @yueshuaing - LMK if this looks good and I can easily implement today.

It looks good to me! Not sure if the roadway property changes will have this issue too, like changing a bike/walk link properties?maybe no. I discussed with Sijia yesterday, we decided to add modes: ["any"] to all roadway_deletion and roadway_property_change project cards. I've tested applying the project cards, it worked fine.

**Comment by e-lo** [comment]
The issue we have in the roadway property changes is that if it is trying to search for a "segment" connecting a from_node and to_node then it could use the sidewalk when we don't want it to...

**Comment by e-lo** [comment]
@yueshuaing check that this is implemented as intended in above commit and then close.

**Comment by yueshuaing** [comment]
> @yueshuaing check that this is implemented as intended in above commit and then close.

It works as intended after fixing a typo in https://github.com/wsp-sag/network_wrangler/pull/355/commits/a4fcf0590bde0dd97411a479746606803b683bcc
