### ISSUE TITLE
[BUG] Maximum recursion error when write out roadway network after applying managed lane project cards

### ISSUE THREAD

**Issue by yueshuaing** [wsp-sag/network_wrangler#367]
## Describe the bug
While trying to use `write_roadway` to write out a standard roadway network after applying managed lane projects in [BaseMnPASS](https://github.com/Metropolitan-Council/project_card_registry/tree/Test1/projects/BaseMnPASS), I got the following error.
```python 
OverflowError: Maximum recursion level reached
```
My current recursion limit is set to 5000. It is possible that the values (e.g., [category='any' timespan=['6:00', '10:00'] value=1] ) stored in the newly added column `sc_ML_lanes` and `sc_lanes` contribute to the issue.

## To Reproduce
1. Load V01 standard networks
2. Apply project cards in [BaseMnPASS](https://github.com/Metropolitan-Council/project_card_registry/tree/Test1/projects/BaseMnPASS)
3. Run `write_roadway` to save the network
![image](https://github.com/user-attachments/assets/92e7ecf7-cfe3-4e84-8e93-9bab79ceb187)
![image](https://github.com/user-attachments/assets/45283048-f507-4d42-8303-b5b585933993)

**Comment by e-lo** [comment]
@yueshuaing did you set `convert_complex_link_properties_to_single_field=True` when calling `write_roadway()`?  I can't tell based on your screenshots

**Comment by yueshuaing** [comment]
> @yueshuaing did you set `convert_complex_link_properties_to_single_field=True` when calling `write_roadway()`? I can't tell based on your screenshots

Thanks! Setting convert_complex_link_properties_to_single_field=True works for me. I'm now having a different error.

**Comment by e-lo** [comment]
That said - we don't want to have an issue when writing it out without that - so see if we can create a minimal viable test that triggers the error in `roadway\test_io.py`.  

i.e. what is the value of one of the scoped link properties that is triggering the recursion issue? (you can just print it out). We can read in a network with that value there and then try and write it out and see what is going on (easier to test than adding all of the projects)

**Comment by yueshuaing** [comment]
They're the values in `sc_ML_lanes` and `sc_lanes`, e.g., [ScopedLinkValueItem(category='any', timespan=['6:00', '10:00'], value=1)]. I can export the network without these two variables. 
![image](https://github.com/user-attachments/assets/fafd9cc6-545e-4043-a4ff-9c6eb1227977)

I tried setting convert_complex_link_properties_to_single_field=True, now I'm having issues in [translate_links_df_v1_to_v0](https://github.com/wsp-sag/network_wrangler/blob/selection-refactor/network_wrangler/roadway/links/io.py#L107). I will share more details later

**Comment by yueshuaing** [comment]
Following up on the issue of [translate_links_df_v1_to_v0](https://github.com/wsp-sag/network_wrangler/blob/selection-refactor/network_wrangler/roadway/links/io.py#L107) above:
I made some code changes (https://github.com/wsp-sag/network_wrangler/commit/6aad831c78a3160c6151c4b0109791a2c45cbd20) to fix the issue in the screenshot below, which occurred while running the `translate_links_df_v1_to_v0` function. The issue is that the values saved in sc_ML_lanes, sc_lanes are ScopedLinkValueItem objects which are not subscriptable.
![image](https://github.com/user-attachments/assets/24106b8e-fe75-4d0c-8aa8-62f5c2287d2b)

Although I'm now able to convert ScopedLinkValueItem objects into dictionaries, these cannot [be assigned to the default property](https://github.com/wsp-sag/network_wrangler/blob/selection-refactor/network_wrangler/models/roadway/converters.py#L192C5-L192C56), i.e. sc_lanes to lanes, because their dtype is incompatible with int64
![image](https://github.com/user-attachments/assets/3b320e68-f25f-4dce-9849-9454b058d5b5)

**Comment by e-lo** [comment]
@yueshuaing - I'm having trouble writing a test using screenshots. Can you either submit a PR with a test (or at least some test data) to the [`selection-refactor`](https://github.com/wsp-sag/network_wrangler/tree/selection-refactor) branch or copy-paste it here?

 ✅  The issue of Class-based vs dict-based types is something we should be consistent about throughout.  The validator object should turn them into `list[ScopedLinkValueItem]` types consistently, so the fix you made to access via dot-notation rather than subscript should be correct.  

🤔  The dictionary type being assigned to lanes just needs to not be validated afterwards and it should be ok.  I'd run the test thru the debugger to see where it is hanging up and accidentally validating (and if it is hidden somewhere that might also explain our run time issue)

**Comment by yueshuaing** [comment]
I added [this line](https://github.com/wsp-sag/network_wrangler/pull/355/commits/70e7d6e1691ed3c61b06394c4b00f7eeed0a5705) before assigning a dictionary directly to a variable of type int64. It successfully completed the translation of the links from df v1 to v0, but had the same recursion issue again when writing out the tables.

This zip file includes a cutout of the test standard network and the project cards
[v01_cut.zip](https://github.com/user-attachments/files/16787339/v01_cut.zip)

**Comment by yueshuaing** [comment]
I added [this line](https://github.com/wsp-sag/network_wrangler/pull/355/commits/70e7d6e1691ed3c61b06394c4b00f7eeed0a5705) before assigning a dictionary directly to a variable of type int64. It now can successfully run through translate_links_df_v1_to_v0.

After further investigation, I found that the recursion issue was actually due to some of my temporary fixes that haven't been checked in yet. I saw a ValidationError saying that a None value couldn't be coerced to type GeoSeries when applying managed lane project cards to the base scenario. I temporarily changed `ML_geometry` and `geometry` to accept any type.

This issue doesn't appear in a small cutout of the network but only occurs in the full network. The full network is too big to be uploaded. I'll send the them via email.

**Comment by e-lo** [comment]
>After further investigation, I found that the recursion issue was actually due to some of my temporary fixes that haven't been checked in yet. 

Gotcha.  So does this mean that there isn't a recursion issue anymore?

**Comment by yueshuaing** [comment]
Yeah, no recursion issue. I revert my temp changes on `ML_geometry` and `geometry data` types. Now the issue is
```python
ValidationError: 1 validation error for _edit_link_property
  Value error, Error while coercing 'ML_geometry' to type geometry: Could not coerce <class 'pandas.core.series.Series'> data_container into type geometry:
```
I think it is because only the managed lanes have valid `ML_geometry`, while the rest of records are None values. During the data model validation, it attempts to convert these records to a GeoSeries.

**Comment by yueshuaing** [comment]
This commit https://github.com/wsp-sag/network_wrangler/commit/1a06561fd26f5a40c2b2f8367c1fab7ed16c7a71 seems to have fixed the issue. While testing with the debugger, I noticed that although `ML_geometry` is defined as GeoSeries, when there are too many `None` values in the column, it might default to being treated as an object type instead, which causes it to fail the validation.
I will proceed testing with the standard network to model network once https://github.com/wsp-sag/network_wrangler/issues/361 is done.

**Comment by e-lo** [comment]
https://github.com/wsp-sag/network_wrangler/commit/3b68343f14ca4ce80e77a1188293ef0fb22415b1 in main `selection-refactor` branch should address the issue.

**Comment by yueshuaing** [comment]
> [3b68343](https://github.com/wsp-sag/network_wrangler/commit/3b68343f14ca4ce80e77a1188293ef0fb22415b1) in main `selection-refactor` branch should address the issue.

The issue still persist. I guess we will need to enforce GeoSeries for the whole `ML_Geometry` column after the geometry of ML links get created.
