### ISSUE TITLE
Timespan is not in increasing order

### ISSUE THREAD

**Issue by yueshuaing** [wsp-sag/network_wrangler#370]
## Describe the bug
This issue occurs when applying a transit_routing_change project card to change the route for the NT period which spans from19:00 to 3:00. The function [str_to_time_list](https://github.com/wsp-sag/network_wrangler/blob/selection-refactor/network_wrangler/utils/time.py#L167) convert this time span to [datetime.datetime(2024, 9, 5, 19, 0), datetime.datetime(2024, 9, 5, 3, 0)], triggering this error message
```python 
ValueError: Timespan is not in increasing order.
```

**Comment by e-lo** [comment]
There are a few options here in order of complexity.
1. we just set the end_time here to midnight
1. we disable this check and know that any durations calculated will be wrong / for wrong day
2. we figure out how to implement #347 (I tried for a bit but no dice)

**Comment by yueshuaing** [comment]
Got it. Can we [disable the error message](https://github.com/wsp-sag/network_wrangler/commit/cb2a3cf7f22d9163edb44661a97b57cfa883fe21) for now? It seems to be working fine in selecting correct transit trips.

**Comment by i-am-sijia** [comment]
> There are a few options here in order of complexity.
> 
> 1. we just set the end_time here to midnight
> 2. we disable this check and know that any durations calculated will be wrong / for wrong day
> 3. we figure out how to implement [[FEATURE] Handle GTFS times > 24 hours #347](https://github.com/wsp-sag/network_wrangler/issues/347) (I tried for a bit but no dice)

What is the duration calculated used for?  Can we do something like if duration <0, duration + 24? Depending on what it is used for, I am fine with option 1 or 2.

**Comment by e-lo** [comment]
Duration is used for checking if there is overlap in scopes. LM see what i can do with your suggestion....

**Comment by e-lo** [comment]
Closing this - but LMK if not satisfied.
