### ISSUE TITLE
Need a newer version of pandera

### ISSUE THREAD

**Issue by yueshuaing** [wsp-sag/network_wrangler#371]
## Describe the bug
This issue is caused by the commits https://github.com/wsp-sag/network_wrangler/commit/b7b3b9196c662c74331a3412d9831e7bce2407bd

@pa.parser("start_time")
@pa.parser("end_time")
@pa.parser("arrival_time")
@pa.parser("departure_time")

```python 
AttributeError: module 'pandera' has no attribute 'parser'
```
### Thoughts on resolution
Upgrade pandera from [0.18.3](https://github.com/wsp-sag/network_wrangler/blob/selection-refactor/environments/conda/environment.yml#L31) to 0.19.0

**Comment by e-lo** [comment]
Fixed in  https://github.com/wsp-sag/network_wrangler/commit/beb00fae2012f0fb2bc83891672b889f32d29a73
