### ISSUE TITLE
Search Method for Affected Roadway Links

### ISSUE THREAD

**Issue by DavidOry** [wsp-sag/network_wrangler#38]
@e-lo to elaborate.

**Comment by DavidOry** [comment]
Initially, it's a simple method but the idea is it returns a set and the action is taken on the set. We can refine the intelligence of how to fetch the vector.

**Comment by e-lo** [comment]
Idea on usage

```
select_roadway_features(self, selection: tuple(str or dict)):
    '''
    Selects roadway features that 

    Example usage:
       net.select_roadway_links(
          selection = [ {'from': {'osmid': '1234'},  # a match condition for the from node using osm, shared streets, or model node # 
                         'to': {'shstid': '4321'},   # a match for the to-node..
                         'facility': {'name':'Main St'},       #a regex or match for facility condition...could be # of lanes, facility type, etc.
                         }, ...
                        ])
    '''
```

**Comment by e-lo** [comment]
put a stub method on this branch: https://github.com/wsp-sag/network_wrangler/tree/change_multiple_links_attributes

**Comment by e-lo** [comment]
The initial pass is working in PR https://github.com/wsp-sag/network_wrangler/pull/47 but doesn't satisfy all use cases and needs to be rigorously tested. Will be creating a notebook to be able to visualize the results.

**Comment by e-lo** [comment]
@kulshresthaa here is a very very rough pseudocode for what we discussed this PM:
https://github.com/wsp-sag/network_wrangler/wiki/Network-search-method

**Comment by e-lo** [comment]
**Question: What should the qualifications be for returning a "good selection"?**
This is showing a path from A-->B that goes along the one-way pair for the specified street because 6th St is one-way the other way.  This seems excessive. 

Thoughts?  cc: @DavidOry @josiekre @kulshresthaa 

![image](https://user-images.githubusercontent.com/794787/62971938-d3bc8600-bdc7-11e9-9c38-a90e4c40f224.png)

**Comment by e-lo** [comment]
Tests pass, calling this good for now.
Opened a separate issue for the criteria for a failing selection.
