### ISSUE TITLE
[BUG] Route Addition Failing

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#382]
## Describe the bug

Edits recently made to the route addition project card fail the test because it requires data outside the standard GTFS network like `agency_raw_name`.  In addition, these edits remove adding any generally added attributes 

### Failing tests

- [ ] `test_add_route_to_feed_dict`

### Triggering line of code

```python
            for i, trip in enumerate(route["trips"]):
                shape_id = fill_str_ids(pd.Series([None]), feed.shapes["shape_id"]).iloc[0]
                add_shape_df = _create_new_shape(trip["routing"], shape_id, road_net)
>               if route["agency_raw_name"]:
E               KeyError: 'agency_raw_name'
```

### Thoughts on resolution

In order of preference:

1. Move this logic/requirement out of base wrangler code and fix issues downstream that require it (still not sure why needed/problem it is solving?)
2. Copy attributes that you need other places generically rather than by specific name
3. At very least, query to see if the column exists before trying to copy it and if so - encasulate all that logic in a single function so it doesn't muddy existing code.

**Comment by yueshuaing** [comment]
Fixed in https://github.com/wsp-sag/network_wrangler/commit/376035cb9545e6ea8df00a64d179efb90a52a5fd, please take a look

**Comment by e-lo** [comment]
The test doesn't pass yet - I'll take a look.

**Comment by e-lo** [comment]
I fixed one small bug where you had treated timespans as a string instead of a tuple, but the test isn't passing because it looks like it added two trips instead of one.  Since you altered the logic, can you investigate and remedy?

To replicate: 

```python
pytest tests/test_transit/test_changes/test
_transit_add_route.py

```

Error in finding the correct trips:
```
       # check trips
        new_trips = updated_feed.trips.loc[updated_feed.trips.route_id.isin(["abc"])]
        new_trip_ids = new_trips.trip_id.to_list()
>       assert len(new_trip_ids) == 1
E       AssertionError: assert 2 == 1
E        +  where 2 = len(['trip0_shp3', 'trip1_shp3'])
```

**Comment by yueshuaing** [comment]
The timespan of headway dictionary is interpreted as string. This is how the loaded headway dictionary look like: {"('6:00', '12:00')": 600}. I updated the `_parse_headway_record` and the headway example.
Yeah, the trips are added for each headway, so there should be two new trips.

I fixed them in https://github.com/wsp-sag/network_wrangler/commit/91dad74842df9315d88900cd491f435e01da0722

**Comment by yueshuaing** [comment]
Fixed in https://github.com/wsp-sag/network_wrangler/commit/466f3f5e1a3367e597ed64d4d9d991184fde2d8e. I moved the adding extra route attributes to metcouncil wrangler
