### ISSUE TITLE
🧹 [CHORE] Update version # in `pyproject.toml` to get release to publish to pypi

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#384]
@yueshuaing when you created a release you forgot to update the version # in `pyproject.toml` which is what PyPI uses to number the releases using semantic versioning - so the publication to PyPI failed.

I think what you should do is:

1. update version #. in `pyproject.toml` (it should actually be beta-1 b/c all features have been added)
2. create a new release 
3. update Rachel's install directions to be from PyPI

NOTE: 

- her install directions do not need to install projectcard. That should happen automagically with requirements specified in pyproject.toml. You could hypothetically update metcouncil wrangler to require network wrangler and then she would only need to install one thing.
- I've updated the environments in the repo and also included a pip.lock file so Rachel could also use these

**Comment by RachelWikenMC** [comment]
I was just about to start installing. should i wait?

**Comment by yueshuaing** [comment]
Got it. 
@RachelWikenMC I believe you can still proceed with testing today as planned. I have a few updates to make to the Network Wrangler for future year workflow testing. Once those changes are complete, I’ll create a new pre-release and update the instructions for you to follow when updating the environment.
@e-lo @RachelWikenMC Would this plan work for you?
