### ISSUE TITLE
[BUG] _add_extra_route_attributes will fail if route doesn't have `agency_raw_name`

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#385]
## Describe the bug
A clear and concise description of what the bug is or the error code you got. e.g. 

Following code in adding transit route will fail if ["agency_raw_name"] is not in routes.

```python 
def _add_extra_route_attributes(
    route: dict, target_df: pd.DataFrame, attributes: list[str] = None
) -> pd.DataFrame:
...
    if attributes is None:
        attributes = ["agency_raw_name"]

    for attr in attributes:
        if attr in route and route[attr]:
            target_df[attr] = route[attr] 
    return target_df
```

### Thoughts on resolution

Delete  ` _add_extra_route_attributes()` function b/c not necessary.  Can fix this by just taking extra attributes that are in project card as an input and assigning them. No need to ever specify "agency_raw_name".

example:

```python
def _create_new_trips(
    trip: dict,
    route: dict,
    trip_id: str,
    shape_id: str,
) -> paDataFrame[TripsTable]:
    """Create new trips for a route.

    Args:
        trip: Trip dictionaries with trip_id, shape_id, and other trip information.
        route: Route dictionaries.
        trip_id: Trip ID for the trips.
        shape_id: Shape ID for the trips.
    """
    SKIP_TRIP_PROPS = ["headway_secs", "routing"]

    new_trip = {
        "route_id": route["route_id"],
        "direction_id": trip.pop("direction_id"),
        "trip_id": trip_id,
        "shape_id": shape_id,
    }
    new_trip.update({k: v for k, v in trip.items() if k not in SKIP_TRIP_PROPS})
    add_trips_df = pd.DataFrame(new_trip)
    return add_trips_df
```

Note: this is similar to previous implementation I redid.

**Comment by yueshuaing** [comment]
okay..I tested the project card without 'agency_raw_name', it worked fine as this line will check if the extra attributes is in the routes `if attr in route and route[attr]:`
I'm a bit concerned about adding all extra attributes that we don't want

**Comment by yueshuaing** [comment]
I'll try moving this function to the downstream as suggested here https://github.com/wsp-sag/network_wrangler/issues/382

**Comment by yueshuaing** [comment]
Fixed in https://github.com/wsp-sag/network_wrangler/commit/466f3f5e1a3367e597ed64d4d9d991184fde2d8e. I moved the adding extra route attributes to metcouncil wrangler
