### ISSUE TITLE
[BUG] Repeated `pd.concat()` and setting `feed.<table_name>` in `_add_route_to_feed()`

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#386]
## Describe the bug

1. `pd.concat()` will lose attributes of any dataframe. 
2. running a `concat`  is  notoriously slow - especially on a larger dfs. 
3. Setting a table value to `net.feed` will also trigger validation **each time**.  So you are doing that for every single trip headway right now for each table (other than route).

### Triggering line of code

```python
for route in add_routes:
       ...
        for trip in route["trips"]:
            ...
            feed.shapes = pd.concat([feed.shapes, add_shape_df], ignore_index=True, sort=False)

            for j, headway in enumerate(trip["headway_secs"]):
                ...
                feed.trips = pd.concat([feed.trips, add_trips_df], ignore_index=True, sort=False)
                feed.frequencies = pd.concat(
                    [feed.frequencies, add_freqs_df], ignore_index=True, sort=False
                )
                feed.stops = pd.concat([feed.stops, add_stops_df], ignore_index=True, sort=False)
                feed.stop_times = pd.concat(
                    [feed.stop_times, add_stop_times_df], ignore_index=True, sort=False
                )
```

### Thoughts on resolution

Preferred approach:

- Change to `utils.data.concat_with_attr` which is a wrapper which will copy attrs.
- Aggregate data for new route in lists of dicts (or visa versa) that are *like* the DF
- Create a single "addition" df for each table-type
- *then* join the final additiona dfs to feed

**Comment by yueshuaing** [comment]
Fixed in https://github.com/wsp-sag/network_wrangler/commit/466f3f5e1a3367e597ed64d4d9d991184fde2d8e. Please take a look and let me know if anything else is needed.
