### ISSUE TITLE
[BUG] Unable to write out previously applied projects from an existing scenario.

### ISSUE THREAD

**Issue by yueshuaing** [wsp-sag/network_wrangler#387]
## Describe the bug
1. I create scenario_B from scenario_A by adding more project cards, calling scenario_B.write() fails to write out the project cards that were applied in scenario_A. This is because those projects are not stored in project_cards. An example can be found in test_scenario_apply_all_projects.py
 ```python
for p in scenario.applied_projects:
>   card = scenario.project_cards[p]
     filename = Path(card.__dict__.get("file", f"{p}.yml")).name
     outpath = outdir / filename
     write_card(card, outpath)
 ```

2. Similarly, if I load a scenario using a scenario.yml file, the scenario only knows which projects have been applied but can't write out those previously applied projects using scenario.write()

## To Reproduce
```python
pytest tests/test_roadway/test_changes/test_scenario_apply_all_projects.py
```

**Comment by e-lo** [comment]
This was actually an intentional behavior as it would get really cumbersome to keep *all* the project cards for *all* the previous scenarios. What is the desired functionality you want to achieve? Or is it crashing when it shouldn't?

**Comment by yueshuaing** [comment]
> This was actually an intentional behavior as it would get really cumbersome to keep _all_ the project cards for _all_ the previous scenarios. What is the desired functionality you want to achieve? Or is it crashing when it shouldn't?

yeah, it crashes in writing out scenario with projects_write set to True. It is because it's looping through all applied projects, but only writes out the project cards applied to the current scenario. 
For Metcouncil workflow, we don't actually need to write out project cards since all projects are stored in project_card_registry. I think this piece of code still makes sense but just need to fix the bug to make it run through.

```python
for p in scenario.applied_projects:
>   card = scenario.project_cards[p]
    filename = Path(card.__dict__.get("file", f"{p}.yml")).name
    outpath = outdir / filename
    write_card(card, outpath)
```

**Comment by e-lo** [comment]
>  just need to fix the bug to make it run through.

10-4. Will address momentarily.

**Comment by e-lo** [comment]
Fixed!
