### ISSUE TITLE
Wrapper method to add managed lanes in RoadwayNetwork - simple version

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#50]
1. Managed lane attachment method: 

For example:
  - separate facility with specific entry/exits to/from mainline 
  - separate lane with specific entry/exits to/from mainline 
  - separate lane with permeable boundary 

2. Managed lane characteristics: copied from mainline or new?
 - including any time of day considerations

QUESTIONS:
- under which conditions do we keep it as an attribute of existing link and shape, or add new link records?  New shape records?

**Comment by e-lo** [comment]
*SIMPLE* strawman to try out, for managed lanes that are not a separate facility:
 - store managed lane as link-level attribute of mainline
 - be as consistent as possible with OSM methods/terms
 - anything related to connector links should be stored at the link level, referencing A-node and B-node (i.e. entry tolls, HOV requirements, etc) - follow combo of ShSt (for AB stuff) and OSM link-level managed lane terms.

**Comment by JonathanEhrlichMC** [comment]
@rachelwikenmc

**Comment by JonathanEhrlichMC** [comment]
@rachelwikenMC How does this strawman look from the perspective of how MnPASS works?

**Comment by RachelWikenMC** [comment]
@JonathanEhrlichMC I would need more info to comment. not sure what "connector links" are in this scenario if we are storing HOV info on mainline.

**Comment by e-lo** [comment]
Let's discuss at our check in on Wednesday.

**Comment by e-lo** [comment]
Fixed in https://github.com/wsp-sag/network_wrangler/pull/68
