### ISSUE TITLE
When listing specific IDs, don't go through big search

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#53]
If the `facility` flag directly specifies IDs, you don't need to do the big network search, you can just do a regular pandas query.

IDs would include:
- Shared Street IDs, 
- OSMIDs, 
- travel model IDs

Proposed approach:
1. create a class-level variable in RoadwayNetwork that is a list of variables that are considered unique IDs
2. update facility query to do simpler querying if a unique ID is used
3. update validation and requirements to not require anything else if a unique id is used

**Comment by kulshresthaa** [comment]
done in 3b16707e81f070413a9cd10147da9612e4fba10f

@e-lo please review. Could you work on updating the validation and requirements to not require anything else if a unique id is used for this part?
