### ISSUE TITLE
TransitNetwork route-level attribute change

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#57]
Be able to:
- consume a route-level transit change project card
- make changes to one or more routes
- output manipulated TransitNetwork object
- make record of any warnings or errors in the log files

**Comment by josiekre** [comment]
The implementation of `apply_roadway_feature_change()` uses `copy.deepcopy(self)` to create a new network return. I've been attempting to keep as much the same as possible for transit, but it seems like this would create a memory/runtime problem in the case of large networks and many attribute changes. 

https://github.com/wsp-sag/network_wrangler/blob/5edd3c07cc44a30e4c386923eebf2ff77c469fbe/network_wrangler/RoadwayNetwork.py#L725-L745

Why not edit the existing network object at `self`, @e-lo?

**Comment by e-lo** [comment]
I think that is probably fine, but let's make it an option?

**Comment by josiekre** [comment]
> I think that is probably fine, but let's make it an option?

10-4
