### ISSUE TITLE
Transit route-level change Project Card Consumption 

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#63]
Update project card read, [project card schema](https://github.com/wsp-sag/network_wrangler/blob/master/schemas/project_card.json), and validation methods to adhere to updates to the project card design.

https://jsonschema.net/ is a useful resource for updating the schema

**Comment by josiekre** [comment]
I think this can now be closed along with #55. Please review @e-lo.

**Comment by josiekre** [comment]
- [ ] Update schema to remove "attribute change" from types of cards
