### ISSUE TITLE
Validate TransitNetwork using Partridge.config object

### ISSUE THREAD

**Issue by josiekre** [wsp-sag/network_wrangler#74]
Partridge does not fail when the trips table is missing oddly. I accidentally renamed `examples/stpaul/trips.txt` to `examples/stpaul/trips.csv`, tried running tests, and took a while to realize that Partridge returns an empty trip table without failing.

We should import or create JSON [Table Schemas](https://frictionlessdata.io/specs/table-schema/) to validate our transit networks against. It works just like JSON Schemas but for tabular data (CSV/TXT) rather than JSON/YML.

See https://github.com/Stephen-Gates/GTFS for an example.

**Comment by e-lo** [comment]
I have used the frictionless data table schemas before and am not a super
big fan as it doesn't have much flexibility.

Partridge is designed to not fail on much, true.

I'd almost prefer that we write our own validation method of the Partridge
config.

**Comment by josiekre** [comment]
The plan is to loop through all the Pandas columns in TransitNetwork.feed and check them using `type()` against the `Partridge.config` object. Fail if mismatching.

**Comment by e-lo** [comment]
Doing this somewhat now.
