### ISSUE TITLE
Update Roadway Property Change Method to use a list of dictionaries 

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#75]
Make sure it works for new project card schema: 

```
- property: abc
  change: 2
- property: def
  set: 1
```

**Comment by josiekre** [comment]
Linking https://github.com/wsp-sag/network_wrangler/issues/63#issuecomment-525506765 for a note on why the change is required.

**Comment by josiekre** [comment]
I made this change to the project cards and schema already if you want to see about cherry picking those. Then you'll only need to update the RoadwayNetwork class.

**Comment by kulshresthaa** [comment]
How would this extend in the case of Managed Lanes project card with TOD information?
```
properties:
  - property: ML_LANES
    set: 1
```

How will the time key be specified if a property can only have set or change?

This is our proposed structure before the change
```
ML_LANES:
  - time: [7:00, 9:00]
    - set: 1
  - set: 0
```

**Comment by kulshresthaa** [comment]
completed with c617c5ab916542e46674cfe9f657f17a60483486
