### ISSUE TITLE
Query transit by route attribute which are consistent with GTFS

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#79]
I should be able to query by attributes of the route table, not just the trip table.

Tried:
```
simple_transit_selection = {"route_short_name": "3"}
selected_trips = transit_net.select_transit_features(simple_transit_selection)

selected_trips
```
got:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-87-f7a1b983d342> in <module>
      1 simple_transit_selection = {"route_short_name": "3"}
----> 2 selected_trips = transit_net.select_transit_features(simple_transit_selection)
      3 
      4 selected_trips

~/Documents/urbanlabs/MetCouncil/working/network_wrangler/network_wrangler/TransitNetwork.py in select_transit_features(self, selection)
    151         else:
    152             WranglerLogger.error("Selection not supported %s", selection.keys())
--> 153             raise ValueError
    154 
    155         # If a time key exists, filter trips using frequency table

ValueError: 
```

**Comment by josiekre** [comment]
@e-lo I'm not at my computer so I cannot test this right now, but you should be able to do:

```
simple_transit_selection = {"short_name": "3"}
selected_trips = transit_net.select_transit_features(simple_transit_selection)

selected_trips
```

Example project card 9 uses `long_name` so this would follow that logic.

**Comment by e-lo** [comment]
Thanks -  I confirmed that this works.
Question: do we drop the `route_` and `trip_` prefixes of all properties with them?

**Comment by josiekre** [comment]
Generally I followed whatever the GTFS standard is. So I believe it is `trip_id`, `route_id`, `short_name`, and `long_name`.

Would you like to go with something else than the GTFS column names?

**Comment by josiekre** [comment]
That's not true actually. I lied. GTFS uses `route_short_name` and `route_long_name`. Shall I switch to that?

https://developers.google.com/transit/gtfs/reference#routestxt

**Comment by e-lo** [comment]
That would be great. I think we should directly use what GTFS uses.

**Comment by josiekre** [comment]
Oh I just put a comment about this on another issue. I'll fix it here.

**Comment by e-lo** [comment]
Fixed in transit route shape PR
