### ISSUE TITLE
Select by multiple tiers of selection doesn't work.

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#80]
I should be able to have multiple tiers of querying on trips/routes, but right ow when I run:
```
simple_transit_selection = {"route_id": "365-111", "wheelchair_accessible":"0"}
selected_trips = transit_net.select_transit_features(simple_transit_selection)

transit_net.feed.trips[transit_net.feed.trips.trip_id.isin(selected_trips)]
```

I get:

![image](https://user-images.githubusercontent.com/794787/65790630-e8a16e80-e114-11e9-9f71-27234fa7dc9c.png)

**Comment by josiekre** [comment]
This kind of opens a big can of worms. Right now transit is built to only handle the following for facility selection: `trip_id`, `route_id`, `short_name`, `long_name`, and `time`. The schema requires one of the first four, and allows optionally `time`. See https://github.com/wsp-sag/network_wrangler/blob/0f06a39b66d1f34d7a71f96113f7c1b1c952f178/network_wrangler/schemas/project_card.json#L69-L183.

If we allow other optional selections, how do we validate them? Do we list all possible variables in `project_card.json` schema? You must have figured out a better solution than that for the road side of things. 

Help me here ;)

**Comment by josiekre** [comment]
On thing that is potentially tricky, is that somewhere in the code we have to associate all the possible variables with either a trip or a route, which is different than on the road network. There I think all variables are for links, correct? (I think we said nodes don't get attributes if I remember correctly.)

**Comment by e-lo** [comment]
I would search through both and use whichever you find first? Finding one
first vs the other shouldn't result in different answers (I think...might
want to test that)

**Comment by josiekre** [comment]
Okay I can do that, but the schema is still a question. Do we allow any field through the schema and let some other error pick it up if it is an invalid variable?

**Comment by josiekre** [comment]
Maybe we talked about this in #74 but delayed implementation. I'll leave the validation for that task.

**Comment by e-lo** [comment]
I'm working on the schema but my internet is down for the AM so it might
not be done today. For now you can skip the validation.

**Comment by josiekre** [comment]
FYI I've written the code as if one of `trip_id`, `route_id`, `route_short_name`, or `route_long_name` are still required.

**Comment by josiekre** [comment]
I wrote a test that gets around the schema validation for now, and the new selection works. 

Once the project card schema is loosened to allow any variable in trips/routes tables, then a project card with additional variables should work too.

**Comment by e-lo** [comment]
Fixed in transit route change PR
