### ISSUE TITLE
Using a 'change' in roadway properties results in a failure

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#82]
Tried this:

```
selected_highway = {
    "link": [{"name": ["I 35E"]}],
    "A": {"osmNodeId": "961117623"},  
    "B": {"osmNodeId": "2564047368"}
}
selected_links   = net.select_roadway_features(selected_highway)
selected_indices = selected_links.index.tolist()

change = {
    'properties': [
      {
          'property': 'LANES',
          'change': 1,
      }
    ]
}

net.links_df["selected_links"] = np.where(
            net.links_df.index.isin(selected_indices), 1, 0
        )
revised_net = net.apply_roadway_feature_change(change['properties'])
```

Resulted in:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-138-1832242bbc8c> in <module>
     11 }
     12 
---> 13 revised_net = net.apply_roadway_feature_change(change['properties'])
     14 revised_net.links_df.loc[selected_indices,][['id','LANES']]

~/Documents/urbanlabs/MetCouncil/working/network_wrangler/network_wrangler/RoadwayNetwork.py in apply_roadway_feature_change(self, properties)
    770         """
    771 
--> 772         self.validate_properties(properties)
    773 
    774         # if the input network does not have selected links flag

~/Documents/urbanlabs/MetCouncil/working/network_wrangler/network_wrangler/RoadwayNetwork.py in validate_properties(self, properties)
    754             )
    755             WranglerLogger.error("\n".join(req_err))
--> 756             raise ValueError()
    757             return False
    758 

ValueError: 
```

**Comment by e-lo** [comment]
BTW if you specify existing it doesn't fail.

i.e.
```
change = {
    'properties': [
      {
          'property': 'LANES',
          'existing': 3,
          'change': 2,
      }
    ]
}
```

**Comment by kulshresthaa** [comment]
yes, because current setup expects "existing" too, if you specify "change", i.e., "existing" and "change" OR "set". 

See [here](https://github.com/wsp-sag/network_wrangler/blob/develop/network_wrangler/RoadwayNetwork.py#L736)

**Comment by e-lo** [comment]
If we leave it this way, that wont allow us to increment by facilities that we want to shrink or grow but which don't have the same values.  i.e. a facility that varies from 3-4 lanes, but we want to designate one of them a transit lane at all times.

I don't believe we have this same restriction in place for transit?

cc: @josiekre

**Comment by josiekre** [comment]
This is not a restriction in place via the schema or the transit implementation.

The schema only requires that either change or set is specified. Existing is always optional.
https://github.com/wsp-sag/network_wrangler/blob/fa34a3120662f9c890a98c0b05871e80a07029a6/network_wrangler/schemas/project_card.json#L184-L229

The transit implementation just checks the existing value against the discovered value but otherwise is not used.
https://github.com/wsp-sag/network_wrangler/blob/fa34a3120662f9c890a98c0b05871e80a07029a6/network_wrangler/TransitNetwork.py#L203-L218

**Comment by e-lo** [comment]
> The schema only requires that either change or set is specified. Existing is always optional.

Yes, I think this is what we want.

**Comment by kulshresthaa** [comment]
done!

**Comment by kulshresthaa** [comment]
new [`validate_properties`](https://github.com/wsp-sag/network_wrangler/blob/develop/network_wrangler/RoadwayNetwork.py#L699) method in 978968af2fce6980b691ed2a8dc17ed76fdc9cb4
