### ISSUE TITLE
simplify API for highway property change

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#83]
The transit property change API is probably the right level:

```
net.apply_transit_feature_change(
            net.select_transit_features(project_card.facility), project_card.properties
        )
```
It is easily applied from a project card, or by specifying the facility and properties individually.

Right now the equiv for highway is much more confusing. We should simplify to the above.
```
selected_links   = net.select_roadway_features(selection_dictionary)
selected_indices = selected_links.index.tolist()
net.links_df["selected_links"] = np.where(
            net.links_df.index.isin(selected_indices), 1, 0
        )
revised_net = net.apply_roadway_feature_change(change['properties'])
```

**Comment by kulshresthaa** [comment]
@e-lo please review the simplification!

**Comment by josiekre** [comment]
PS Maybe piping automatically works? I am a big fan of piping in the style of R's tidyverse pipes. In Python I think piping works like this:

```
(net.pipe(select_transit_features, project_card.facility)
     pipe(apply_transit_feature_change, project_card.properties)
)
```

See https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.pipe.html.

Admittedly, piping is maybe better in R's implementation. R would look something like this slightly more readable version:

```
net %>%
  select_transit_features(project_card.facility) %>%
  apply_transit_feature_change(project_card.properties)
```

**Comment by e-lo** [comment]
I think we are good to go here!
