### ISSUE TITLE
Allow ad-hoc variables in network

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#90]
Confirm ability to add and manage additional network attributes which aren't in the 'standard' network format per MetCouncil request.

**Comment by e-lo** [comment]
1. A project card which has `existing` or `change` to a feature should require that that feature already be on the network (or at least throw a fit if it isn't)
2. If we `set` a new field in a project card (even one not in OPTIONAL_FIELDS), we shouldn't be picky about what that is...we should even allow MetCouncil to add new fields that are specific to them in a project card, but maybe just throw a warning.

**Comment by kulshresthaa** [comment]
I agree. "Set" or "Change" is required for each feature (to be added/updated) in the project card. If the feature has "change", we need to make sure the feature exist on the network or throw an error. If it is "Set", we don't care. Wrangler should add a new feature with the set value.

**Comment by e-lo** [comment]
Confirmed and tested. 
cc to @JonathanEhrlichMC confirming that you have this functionality.
