### ISSUE TITLE
copied network or updated network?

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#95]
One inconsistency that I see right now between transit and roadway approaches that we should resolve is whether we return a copy of an updated network (what happens right now in roadway) or if we modify the network in place (what happens right now in transit).

My sense is that it is cleaner to do it in place because we don't have to worry about the return of the function and making sure we use that...but I'm wondering if there is a reason why we might want to use copy?

cc: @josiekre @kulshresthaa

**Comment by kulshresthaa** [comment]
I changed Roadway to modify the network in place (and have option to return a copy of updated network) in this commit f254fb73843ff0012288f8819a4ad05ae8587716

[Here](https://github.com/wsp-sag/network_wrangler/blob/develop/network_wrangler/RoadwayNetwork.py#L801) and in_place default is True. 

@e-lo where are you seeing Roadway returning copy of an updated network?

**Comment by e-lo** [comment]
doh - for some reason I was only looking at the bottom of the function...we are all good. Sorry!
