### ISSUE TITLE
Allow for multiple facilities to have same changes

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#98]
Desired outcome: be able to apply the same change to disjointed (not contiguous) facilities, i.e. [here](https://github.com/wsp-sag/network_wrangler/blob/5eec644b5ccfc7fe7091ec46d6c596d6f8d73230/example/stpaul/project_cards/wideningMinneahahaPkwy.yml#L3)

Implementation options (not mutually exclusive):
1. Add option to apply the change to the opposite direction (if it exists) with the flag: `apply_to_reverse: True`

2. Allow `facility` to be a list.

Other ideas are certainly worthwhile considering if anybody has some!

cc: @i-am-sijia

**Comment by e-lo** [comment]
Fixed ability in code and then added an issue to fix the data schema as #96

**Comment by e-lo** [comment]
cc to @kulshresthaa  @i-am-sijia  and @josiekre for your feedback on how to implement.

@i-am-sijia is waiting on this for Lasso project card implementation.

**Comment by josiekre** [comment]
I think both options above are valid and should be implemented. I think allowing facility to be a list is more important.

**Comment by josiekre** [comment]
Looks like transit is built already for this. I assumed this would happen eventually, so the first thing I did was convert any of the facility items to a list if it was not already. See https://github.com/wsp-sag/network_wrangler/blob/0f06a39b66d1f34d7a71f96113f7c1b1c952f178/network_wrangler/TransitNetwork.py#L163-L166.

The schema does not allow a list yet though.

**Comment by josiekre** [comment]
Wrote some tests and they are passing. See commit coming with this issue referenced.

**Comment by e-lo** [comment]
@josiekre - it seem as though transit will work this way so long as it is in the same time period...but what if I wanted to change them for all time periods? or some from each?  At this point I think this is an OK limitation, but we should just be explicit about if we can handle it or not.

**Comment by josiekre** [comment]
Yes I see what you mean. If we change from `time: [str, str]` to `start_time` and `end_time`, the solution will be fixable I think. In this case, we no longer have time as a special case to filter on, but would instead treat it like any other optional variable and search through the trips, routes, and freqs table match and then filter trips. See https://github.com/wsp-sag/network_wrangler/blob/b23d34d7a392531a04d264dd6bc76491aa5a3a91/network_wrangler/TransitNetwork.py#L199-L224 on the `transit_routeshape` branch.

**Comment by kulshresthaa** [comment]
@e-lo Are we changing the `facility` to be a list on the roadway side for this? How would facility items look in a project card for a multiple facility selection, any example? Are we specifying those multiple facilities based on some unique identifiers only (say LINK_ID)?

**Comment by kulshresthaa** [comment]
@e-lo thoughts? I need an example of how facility list would look like to apply this.

**Comment by e-lo** [comment]
@kulshresthaa I think you can somewhat design what it would look like, but the idea would be to avoid project files that look like `wideningMinneahahaPkwy.yml` where there are two things that bug me:
1. essentially the same action is performed on a zillion different links (since distance can be calculated)
2. the A, B, and links in the `facility` sections are listed in a manner that makes it easy to make mistakes because it depends on ordering.

If I were to take a stab at a format, I would start with something like:

```
  facility:
    link:
      model_link_id:
      - 194599   #a list of links
         266919
         123456
```
Without requiring AB for unique identifiers

and maybe also allow:

```
  facility:
    A:
      model_node_id:
      - 88788
    B:
      model_node_id:
      - 119366
    link:
      name:
      - "anyname"
    apply_to_reverse: True
```



```

**Comment by kulshresthaa** [comment]
so start by specifying those multiple facilities based on some unique identifiers only (say model_link_id) and then expand?

**Comment by kulshresthaa** [comment]
although, have we not done this part of the issue in #53? Selecting multiple facility based on some id (or other unique identifiers) and then A/B aren't used.

**Comment by kulshresthaa** [comment]
#53 handles selecting multiple links based on list of unique identifiers specified in the project card. Specifying the project card correctly will be taken care in lasso.
