### ISSUE TITLE
Make variable names consistently formed

### ISSUE THREAD

**Issue by e-lo** [wsp-sag/network_wrangler#99]
Desired outcomes: 
- all (eventual) cube network variables should be <10 characters to be able to be represented in a dbf/shp [ note, this could be through a crosswalk later ]
- all variables are consistently UPPER/lower/caMel/under_score
- all variable names are legible
- all variable names that could be consistent with ShSt and OSM, should be

Right now, I think that means:
- OSM uses underscores and lowercase...so let's try and respect that.
- `ASSGN_GRP` = [`highway`](https://wiki.openstreetmap.org/wiki/Key:highway#Roads)
- propose that `T_MANTIME` becomes `transit_time`
- `LINK_ID` becomes `model_link_id` with it's friend becoming `model_node_id`

cc: @josiekre @kulshresthaa

**Comment by e-lo** [comment]
@i-am-sijia  updated the file https://github.com/wsp-sag/client_met_council_network in to match[ this schema](https://github.com/wsp-sag/client_met_council_wrangler_utilities/wiki/Highway-Network).  I will copy the st paul test network into network wrangler

**Comment by i-am-sijia** [comment]
commit [bdb0b50](https://github.com/wsp-sag/client_met_council_network/commit/bdb0b50d31c92221d0f9480705059245703ebe8b)

**Comment by e-lo** [comment]
implemented.
